package branding

import (
	"os"
	"runtime/debug"
	"strings"
	"sync"
)

const (
	defaultProductName = "ad-event-processor"
	defaultVendorName  = "ad-event-processor"

	HTTPSafeViewHeader = "X-ad-event-processor-Safe-View"

	HTTPSafePageHeader = "X-ad-event-processor-Safe-Page"
)

var (
	productName     string
	vendorName      string
	siteURL         string
	supportEmail    string
	supportURL      string
	adminConsoleURL string
	once            sync.Once
)

func initFromEnv() {
	productName = envOr("BRAND_PRODUCT_NAME", defaultProductName)
	vendorName = envOr("BRAND_VENDOR_NAME", defaultVendorName)
	siteURL = strings.TrimSpace(os.Getenv("BRAND_SITE_URL"))
	supportEmail = strings.TrimSpace(os.Getenv("BRAND_SUPPORT_EMAIL"))
	supportURL = strings.TrimSpace(os.Getenv("BRAND_SUPPORT_URL"))
	adminConsoleURL = strings.TrimSpace(os.Getenv("BRAND_ADMIN_URL"))
}

func envOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}

func ProductName() string {
	once.Do(initFromEnv)
	return productName
}

func VendorName() string {
	once.Do(initFromEnv)
	return vendorName
}

func SiteURL() string {
	once.Do(initFromEnv)
	return siteURL
}

func SupportEmail() string {
	once.Do(initFromEnv)
	return supportEmail
}

func SupportURL() string {
	once.Do(initFromEnv)
	if supportURL != "" {
		return supportURL
	}
	return siteURL
}

func AdminConsoleURL() string {
	once.Do(initFromEnv)
	return adminConsoleURL
}

func GeneratedConfigHeader() string {
	return "# Generated by " + ProductName() + " platform config - do not edit by hand"
}

func AlertTitle(subject string) string {
	return ProductName() + ": " + subject
}

func HTTPUserAgent(component string) string {
	once.Do(initFromEnv)
	return ProductName() + "-" + component + "/" + Version()
}

func Version() string {
	if info, ok := debug.ReadBuildInfo(); ok && info.Main.Version != "" && info.Main.Version != "(devel)" {
		return info.Main.Version
	}
	return "dev"
}
