version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: monthly
      day: monday
    open-pull-requests-limit: 1
    groups:
      go-patch-minor:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
