import type { RouteDef } from './router_types.js';

export const APP_ROUTES = [
  {
    path: '/bootstrap',
    shell: false,
    load: () => import('../views/bootstrap.js'),
  },
  {
    path: '/install/done',
    shell: false,
    load: () => import('../views/install_done.js'),
  },
  { path: '/', load: () => import('../views/overview.js') },
  { path: '/customers', load: () => import('../views/customers.js') },
  { path: '/customers/:id', load: () => import('../views/customer_detail.js') },
  { path: '/campaigns', load: () => import('../views/campaigns.js') },
  { path: '/campaigns/portfolio', load: () => import('../views/buyer_portfolio.js') },
  { path: '/campaigns/:id', load: () => import('../views/campaign_detail.js') },
  { path: '/campaigns/:id/telegram', load: () => import('../views/campaign_telegram.js') },
  { path: '/dashboards/:role', load: () => import('../views/role_dashboard.js') },
  { path: '/billing', load: () => import('../views/billing.js') },
  { path: '/billing/invoices/:id', load: () => import('../views/invoice_detail.js') },
  { path: '/reports', load: () => import('../views/reports_hub.js') },
  { path: '/reports/placements', load: () => import('../views/reports_placements.js') },
  { path: '/reports/keywords', load: () => import('../views/reports_keywords.js') },
  { path: '/reports/ivt-by-source', load: () => import('../views/reports_ivt.js') },
  { path: '/reports/traffic-sources', load: () => import('../views/reports_traffic.js') },
  { path: '/reports/geo-roi', load: () => import('../views/reports_geo.js') },
  {
    path: '/reports/spend-velocity',
    load: () => import('../views/reports_extended.js').then((m) => ({ mount: m.mountSpendVelocity })),
  },
  {
    path: '/reports/daypart-heatmap',
    load: () => import('../views/reports_extended.js').then((m) => ({ mount: m.mountDaypartHeatmap })),
  },
  {
    path: '/reports/campaign-geo-device',
    load: () => import('../views/reports_extended.js').then((m) => ({ mount: m.mountCampaignGeoDevice })),
  },
  {
    path: '/reports/source-quality',
    load: () => import('../views/reports_extended.js').then((m) => ({ mount: m.mountSourceQuality })),
  },
  {
    path: '/reports/discrepancy-buy-sell',
    load: () => import('../views/reports_extended.js').then((m) => ({ mount: m.mountDiscrepancyBuySell })),
  },
  {
    path: '/reports/true-roi',
    load: () => import('../views/reports_extended.js').then((m) => ({ mount: m.mountTrueROI })),
  },
  {
    path: '/reports/campaign-overview',
    load: () => import('../views/reports_extended.js').then((m) => ({ mount: m.mountCampaignOverview })),
  },
  {
    path: '/reports/customer-portfolio',
    load: () => import('../views/reports_extended.js').then((m) => ({ mount: m.mountCustomerPortfolio })),
  },
  { path: '/reports/telegram', load: () => import('../views/reports_telegram.js') },
  { path: '/reports/telegram/funnel', load: () => import('../views/reports_telegram_funnel.js') },
  { path: '/reports/telegram/bots', load: () => import('../views/reports_telegram_bots.js') },
  { path: '/reports/telegram/premium', load: () => import('../views/reports_telegram_premium.js') },
  { path: '/reports/telegram/fraud', load: () => import('../views/reports_telegram_fraud.js') },
  { path: '/reports/:reportKey', load: () => import('../views/report_stub.js') },
  { path: '/rtb/integration', load: () => import('../views/rtb_integration.js') },
  { path: '/rtb/deals', load: () => import('../views/rtb_deals.js') },
  { path: '/ops', load: () => import('../views/ops_home.js') },
  { path: '/ops/shards', load: () => import('../views/ops_shards.js') },
  { path: '/ops/blacklist', load: () => import('../views/ops_blacklist.js') },
  { path: '/ops/recon', load: () => import('../views/ops_recon.js') },
  { path: '/audit', load: () => import('../views/audit.js') },
  { path: '/settings', load: () => import('../views/settings.js') },
  { path: '/settings/license', load: () => import('../views/settings_license.js') },
  { path: '/settings/domains', load: () => import('../views/settings_domains.js') },
  { path: '/integrations/cost-sync', load: () => import('../views/integrations_cost_sync.js') },
  { path: '/margin-guard', load: () => import('../views/integrations_margin_guard.js') },
  { path: '/integrations/margin-guard', load: () => import('../views/integrations_margin_guard.js') },
  { path: '/integrations/smart-alerts', load: () => import('../views/integrations_smart_alerts.js') },
  { path: '/smart-alerts', load: () => import('../views/integrations_smart_alerts.js') },
  { path: '/integrations/supply', load: () => import('../views/integrations_supply.js') },
  { path: '/dev/components', load: () => import('../ui/dev_components.js') },
] as unknown as RouteDef[];
