apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-control.yaml
  - service-management.yaml
  - service-management-nodeport.yaml
  - service-payment.yaml
  - service-payment-nodeport.yaml
  - service-processor.yaml
  - service-processor-nodeport.yaml
  - deployment-ivt-detector.yaml
