apiVersion: v1
kind: Service
metadata:
  name: management
  namespace: espx
  labels:
    app.kubernetes.io/name: management
    app.kubernetes.io/part-of: espx
spec:
  selector:
    app.kubernetes.io/name: control
  ports:
    - name: http
      port: 8188
      targetPort: http
    - name: udp-control
      port: 8190
      targetPort: udp-control
      protocol: UDP
