
ssl_certificate     /etc/nginx/certs/edge-dev.crt;
ssl_certificate_key /etc/nginx/certs/edge-dev.key;
ssl_protocols       TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers off;


ssl_conf_command Options KTLS;
