#!/usr/bin/env bash
# Role: Render static marketing site Caddy site block for bidshard.com (or MARKETING_DOMAIN).
# Env: MARKETING_DOMAIN (default bidshard.com); MARKETING_ROOT in container (default /srv/marketing).
# Verify: MARKETING_DOMAIN=bidshard.com bash scripts/ops/render_marketing_caddy.sh && cat deploy/ingress/caddy/generated/marketing.caddy
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/lib/paths.sh"
cd "$ROOT"

if [[ -f deploy/installer/install.env ]]; then
  set -a
  # shellcheck disable=SC1091
  source deploy/installer/install.env
  set +a
fi
if [[ -f .env ]]; then
  set -a
  # shellcheck disable=SC1091
  source .env
  set +a
fi

MARKETING_DOMAIN="${MARKETING_DOMAIN:-bidshard.com}"
MARKETING_ROOT="${MARKETING_ROOT:-/srv/marketing}"
OUT="$ROOT/deploy/ingress/caddy/generated/marketing.caddy"

mkdir -p "$(dirname "$OUT")"

{
  echo "# Generated by scripts/ops/render_marketing_caddy.sh — do not edit on host."
  echo "${MARKETING_DOMAIN}, www.${MARKETING_DOMAIN} {"
  echo "	root * ${MARKETING_ROOT}"
  echo "	encode gzip zstd"
  echo "	@installer path /get.sh"
  echo "	header @installer Cache-Control \"no-store\""
  echo "	header @installer Content-Type \"text/plain; charset=utf-8\""
  echo "	@releases path /releases/*"
  echo "	header @releases Cache-Control \"public, max-age=3600\""
  echo "	header Cache-Control \"public, max-age=300\""
  echo "	file_server"
  echo "}"
} > "$OUT"

echo "render_marketing_caddy: wrote ${OUT} for https://${MARKETING_DOMAIN}"
