// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package edge

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type EdgeEdgeConfig struct {
	_                  structs.HostLayout
	SynLimit           uint32
	PpsRate            uint32
	GlobalSynLimit     uint32
	AssumedCpus        uint32
	SynSubnetLimit     uint32
	SynCookieEnabled   uint32
	FingerprintEnabled uint32
}

type EdgeIn6Addr struct {
	_    structs.HostLayout
	In6U struct {
		_       structs.HostLayout
		U6Addr8 [16]uint8
	}
}

type EdgeIpv4LpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      uint32
}

type EdgeIpv6LpmKey struct {
	_         structs.HostLayout
	Prefixlen uint32
	Addr      [16]uint8
}

type EdgePpsBucket struct {
	_      structs.HostLayout
	LastNs uint64
	Tokens uint32
	_      [4]byte
}

type EdgeSynState struct {
	_             structs.HostLayout
	WindowStartNs uint64
	Count         uint32
	_             [4]byte
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	EdgeMapAllowV4              = "allow_v4"
	EdgeMapAllowV6              = "allow_v6"
	EdgeMapBlocklistHostV4      = "blocklist_host_v4"
	EdgeMapBlocklistHostV6      = "blocklist_host_v6"
	EdgeMapBlocklistV4          = "blocklist_v4"
	EdgeMapBlocklistV6          = "blocklist_v6"
	EdgeMapConfig               = "config"
	EdgeMapFingerprints         = "fingerprints"
	EdgeMapGlobalSyn            = "global_syn"
	EdgeMapProgArray            = "prog_array"
	EdgeMapRatelimitV4          = "ratelimit_v4"
	EdgeMapRstRatelimitV4       = "rst_ratelimit_v4"
	EdgeMapStats                = "stats"
	EdgeMapSynRatelimitV4       = "syn_ratelimit_v4"
	EdgeMapSynSubnetRatelimitV4 = "syn_subnet_ratelimit_v4"
	EdgeMapViolations           = "violations"
	EdgeProgXdpEdgeFilter       = "xdp_edge_filter"
	EdgeProgXdpSynCookie        = "xdp_syn_cookie"
)

// LoadEdge returns the embedded CollectionSpec for Edge.
func LoadEdge() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_EdgeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Edge: %w", err)
	}

	return spec, err
}

// LoadEdgeObjects loads Edge and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*EdgeObjects
//	*EdgePrograms
//	*EdgeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadEdgeObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := LoadEdge()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// EdgeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type EdgeSpecs struct {
	EdgeProgramSpecs
	EdgeMapSpecs
	EdgeVariableSpecs
}

// EdgeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type EdgeProgramSpecs struct {
	XdpEdgeFilter *ebpf.ProgramSpec `ebpf:"xdp_edge_filter"`
	XdpSynCookie  *ebpf.ProgramSpec `ebpf:"xdp_syn_cookie"`
}

// EdgeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type EdgeMapSpecs struct {
	AllowV4              *ebpf.MapSpec `ebpf:"allow_v4"`
	AllowV6              *ebpf.MapSpec `ebpf:"allow_v6"`
	BlocklistHostV4      *ebpf.MapSpec `ebpf:"blocklist_host_v4"`
	BlocklistHostV6      *ebpf.MapSpec `ebpf:"blocklist_host_v6"`
	BlocklistV4          *ebpf.MapSpec `ebpf:"blocklist_v4"`
	BlocklistV6          *ebpf.MapSpec `ebpf:"blocklist_v6"`
	Config               *ebpf.MapSpec `ebpf:"config"`
	Fingerprints         *ebpf.MapSpec `ebpf:"fingerprints"`
	GlobalSyn            *ebpf.MapSpec `ebpf:"global_syn"`
	ProgArray            *ebpf.MapSpec `ebpf:"prog_array"`
	RatelimitV4          *ebpf.MapSpec `ebpf:"ratelimit_v4"`
	RstRatelimitV4       *ebpf.MapSpec `ebpf:"rst_ratelimit_v4"`
	Stats                *ebpf.MapSpec `ebpf:"stats"`
	SynRatelimitV4       *ebpf.MapSpec `ebpf:"syn_ratelimit_v4"`
	SynSubnetRatelimitV4 *ebpf.MapSpec `ebpf:"syn_subnet_ratelimit_v4"`
	Violations           *ebpf.MapSpec `ebpf:"violations"`
}

// EdgeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type EdgeVariableSpecs struct {
}

// EdgeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadEdgeObjects or ebpf.CollectionSpec.LoadAndAssign.
type EdgeObjects struct {
	EdgePrograms
	EdgeMaps
	EdgeVariables
}

func (o *EdgeObjects) Close() error {
	return _EdgeClose(
		&o.EdgePrograms,
		&o.EdgeMaps,
	)
}

// EdgeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadEdgeObjects or ebpf.CollectionSpec.LoadAndAssign.
type EdgeMaps struct {
	AllowV4              *ebpf.Map `ebpf:"allow_v4"`
	AllowV6              *ebpf.Map `ebpf:"allow_v6"`
	BlocklistHostV4      *ebpf.Map `ebpf:"blocklist_host_v4"`
	BlocklistHostV6      *ebpf.Map `ebpf:"blocklist_host_v6"`
	BlocklistV4          *ebpf.Map `ebpf:"blocklist_v4"`
	BlocklistV6          *ebpf.Map `ebpf:"blocklist_v6"`
	Config               *ebpf.Map `ebpf:"config"`
	Fingerprints         *ebpf.Map `ebpf:"fingerprints"`
	GlobalSyn            *ebpf.Map `ebpf:"global_syn"`
	ProgArray            *ebpf.Map `ebpf:"prog_array"`
	RatelimitV4          *ebpf.Map `ebpf:"ratelimit_v4"`
	RstRatelimitV4       *ebpf.Map `ebpf:"rst_ratelimit_v4"`
	Stats                *ebpf.Map `ebpf:"stats"`
	SynRatelimitV4       *ebpf.Map `ebpf:"syn_ratelimit_v4"`
	SynSubnetRatelimitV4 *ebpf.Map `ebpf:"syn_subnet_ratelimit_v4"`
	Violations           *ebpf.Map `ebpf:"violations"`
}

func (m *EdgeMaps) Close() error {
	return _EdgeClose(
		m.AllowV4,
		m.AllowV6,
		m.BlocklistHostV4,
		m.BlocklistHostV6,
		m.BlocklistV4,
		m.BlocklistV6,
		m.Config,
		m.Fingerprints,
		m.GlobalSyn,
		m.ProgArray,
		m.RatelimitV4,
		m.RstRatelimitV4,
		m.Stats,
		m.SynRatelimitV4,
		m.SynSubnetRatelimitV4,
		m.Violations,
	)
}

// EdgeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadEdgeObjects or ebpf.CollectionSpec.LoadAndAssign.
type EdgeVariables struct {
}

// EdgePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadEdgeObjects or ebpf.CollectionSpec.LoadAndAssign.
type EdgePrograms struct {
	XdpEdgeFilter *ebpf.Program `ebpf:"xdp_edge_filter"`
	XdpSynCookie  *ebpf.Program `ebpf:"xdp_syn_cookie"`
}

func (p *EdgePrograms) Close() error {
	return _EdgeClose(
		p.XdpEdgeFilter,
		p.XdpSynCookie,
	)
}

func _EdgeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed edge_bpfel.o
var _EdgeBytes []byte
