package openapi

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"ad-event-processor/internal/controlplane"

	"gopkg.in/yaml.v3"
)

const (
	OpenAPIDir            = "api/openapi"
	GeneratedRoutesRel    = "paths/_generated_routes.yaml"
	BundleRel             = "openapi.bundle.yaml"
	MainSpecRel           = "openapi.yaml"
	ParityAllowlistRel    = "parity_allowlist.txt"
	generatedRoutesHeader = "# Generated by cmd/openapi-export; DO NOT EDIT.\n"
)

// DocumentedRoutes are fully specified in hand-maintained path fragments.
var DocumentedRoutes = map[string]struct{}{}

// Export writes generated route stubs and a bundled spec for Spectral.
func Export(repoRoot string) error {
	openAPIDir := filepath.Join(repoRoot, OpenAPIDir)
	generatedPath := filepath.Join(openAPIDir, GeneratedRoutesRel)
	bundlePath := filepath.Join(openAPIDir, BundleRel)
	mainPath := filepath.Join(openAPIDir, MainSpecRel)

	stubs, err := buildGeneratedStubs(controlplane.Catalog())
	if err != nil {
		return err
	}
	if err := writeGeneratedRoutes(generatedPath, stubs); err != nil {
		return err
	}
	return writeBundle(mainPath, generatedPath, bundlePath)
}

func buildGeneratedStubs(routes []controlplane.Route) (map[string]any, error) {
	stubs := make(map[string]any)
	seenOp := make(map[string]struct{})

	for _, route := range routes {
		key := route.Key()
		if _, documented := DocumentedRoutes[key]; documented {
			continue
		}
		opID, err := uniqueOperationID(route, seenOp)
		if err != nil {
			return nil, err
		}
		method := strings.ToLower(route.Method)
		pathItem, ok := stubs[route.Path].(map[string]any)
		if !ok {
			pathItem = map[string]any{}
			stubs[route.Path] = pathItem
		}
		pathItem[method] = map[string]any{
			"tags":        []string{routeTag(route.Path)},
			"operationId": opID,
			"summary":     "Route stub; schema not yet documented",
			"description": "Route stub; schema not yet documented",
			"responses": map[string]any{
				"200": map[string]any{"description": "OK"},
				"default": map[string]any{
					"$ref": "openapi.yaml#/components/responses/Error",
				},
			},
		}
		if params := pathParameters(route.Path); len(params) > 0 {
			pathItem[method].(map[string]any)["parameters"] = params
		}
	}
	return stubs, nil
}

func routeTag(path string) string {
	parts := strings.Split(strings.Trim(path, "/"), "/")
	if len(parts) >= 3 && parts[0] == "api" && parts[1] == "v1" {
		return parts[2]
	}
	return "controlplane"
}

func uniqueOperationID(route controlplane.Route, seen map[string]struct{}) (string, error) {
	base := operationID(route)
	if _, ok := seen[base]; !ok {
		seen[base] = struct{}{}
		return base, nil
	}
	for i := 2; i < 100; i++ {
		candidate := fmt.Sprintf("%s%d", base, i)
		if _, ok := seen[candidate]; !ok {
			seen[candidate] = struct{}{}
			return candidate, nil
		}
	}
	return "", fmt.Errorf("openapi export: could not allocate operationId for %s", route.Key())
}

func operationID(route controlplane.Route) string {
	parts := strings.Split(strings.Trim(route.Path, "/"), "/")
	var b strings.Builder
	b.WriteString(strings.ToLower(route.Method))
	for _, part := range parts {
		if part == "api" || part == "v1" {
			continue
		}
		if strings.HasPrefix(part, "{") && strings.HasSuffix(part, "}") {
			part = "By" + camelCase(strings.Trim(part, "{}"))
		} else {
			part = camelCase(part)
		}
		b.WriteString(part)
	}
	return b.String()
}

func camelCase(s string) string {
	s = strings.ReplaceAll(s, "-", "_")
	chunks := strings.Split(s, "_")
	for i, chunk := range chunks {
		if chunk == "" {
			continue
		}
		chunks[i] = strings.ToUpper(chunk[:1]) + chunk[1:]
	}
	return strings.Join(chunks, "")
}

func pathParameters(routePath string) []map[string]any {
	parts := strings.Split(routePath, "/")
	params := make([]map[string]any, 0)
	for _, part := range parts {
		if !strings.HasPrefix(part, "{") || !strings.HasSuffix(part, "}") {
			continue
		}
		name := strings.Trim(part, "{}")
		params = append(params, map[string]any{
			"name":     name,
			"in":       "path",
			"required": true,
			"schema": map[string]any{
				"type": "string",
			},
		})
	}
	return params
}

func writeGeneratedRoutes(path string, stubs map[string]any) error {
	keys := make([]string, 0, len(stubs))
	for path := range stubs {
		keys = append(keys, path)
	}
	sort.Strings(keys)

	ordered := make(map[string]any, len(stubs))
	for _, path := range keys {
		ordered[path] = stubs[path]
	}

	payload := map[string]any{"paths": ordered}
	body, err := yaml.Marshal(payload)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, append([]byte(generatedRoutesHeader), body...), 0o644)
}

func writeBundle(mainPath, generatedPath, bundlePath string) error {
	mainRaw, err := os.ReadFile(mainPath)
	if err != nil {
		return err
	}
	var mainDoc map[string]any
	if err := yaml.Unmarshal(mainRaw, &mainDoc); err != nil {
		return err
	}

	genRaw, err := os.ReadFile(generatedPath)
	if err != nil {
		return err
	}
	var genDoc map[string]any
	if err := yaml.Unmarshal(stripGeneratedHeader(genRaw), &genDoc); err != nil {
		return err
	}

	mainPaths, _ := mainDoc["paths"].(map[string]any)
	genPaths, _ := genDoc["paths"].(map[string]any)
	if mainPaths == nil {
		mainPaths = map[string]any{}
	}
	if genPaths == nil {
		genPaths = map[string]any{}
	}
	for path, item := range genPaths {
		if _, exists := mainPaths[path]; exists {
			return fmt.Errorf("openapi export: generated path overlaps documented path %s", path)
		}
		mainPaths[path] = item
	}
	mainDoc["paths"] = mainPaths

	body, err := yaml.Marshal(mainDoc)
	if err != nil {
		return err
	}
	return os.WriteFile(bundlePath, body, 0o644)
}

func stripGeneratedHeader(raw []byte) []byte {
	s := string(raw)
	if strings.HasPrefix(s, "#") {
		if idx := strings.Index(s, "\n"); idx >= 0 {
			return []byte(s[idx+1:])
		}
	}
	return raw
}

// RouteKeysFromSpecUnion returns METHOD PATH keys from openapi.yaml paths and generated stubs.
func RouteKeysFromSpecUnion(repoRoot string) (map[string]struct{}, error) {
	openAPIDir := filepath.Join(repoRoot, OpenAPIDir)
	mainPath := filepath.Join(openAPIDir, MainSpecRel)
	generatedPath := filepath.Join(openAPIDir, GeneratedRoutesRel)

	out := make(map[string]struct{})
	if err := addPathKeysFromFile(mainPath, out); err != nil {
		return nil, err
	}
	if err := addPathKeysFromFile(generatedPath, out); err != nil {
		return nil, err
	}
	return out, nil
}

func addPathKeysFromFile(path string, out map[string]struct{}) error {
	raw, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	raw = stripGeneratedHeader(raw)

	var doc map[string]any
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		return err
	}
	paths, _ := doc["paths"].(map[string]any)
	fileDir := filepath.Dir(path)
	for routePath, item := range paths {
		pathItemMap, ok := item.(map[string]any)
		if !ok {
			continue
		}
		if ref, ok := pathItemMap["$ref"].(string); ok {
			resolved, err := resolvePathRef(fileDir, ref)
			if err != nil {
				return err
			}
			pathItemMap = resolved
		}
		for method := range pathItemMap {
			switch strings.ToUpper(method) {
			case "GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS":
				out[strings.ToUpper(method)+" "+routePath] = struct{}{}
			}
		}
	}
	return nil
}

func resolvePathRef(baseDir, ref string) (map[string]any, error) {
	parts := strings.SplitN(ref, "#", 2)
	if len(parts) != 2 {
		return nil, fmt.Errorf("openapi: invalid path ref %q", ref)
	}
	refPath := filepath.Join(baseDir, parts[0])
	raw, err := os.ReadFile(refPath)
	if err != nil {
		return nil, err
	}
	var doc map[string]any
	if err := yaml.Unmarshal(raw, &doc); err != nil {
		return nil, err
	}
	ptr := strings.TrimPrefix(parts[1], "/")
	if !strings.HasPrefix(ptr, "paths/") {
		return nil, fmt.Errorf("openapi: path ref must start with paths/: %q", ref)
	}
	encodedKey := strings.TrimPrefix(ptr, "paths/")
	pathKey := strings.ReplaceAll(encodedKey, "~1", "/")
	paths, _ := doc["paths"].(map[string]any)
	pathItem, ok := paths[pathKey].(map[string]any)
	if !ok {
		return nil, fmt.Errorf("openapi: path ref %q did not resolve to path item", ref)
	}
	return pathItem, nil
}

// LoadParityAllowlist reads METHOD PATH rows from parity_allowlist.txt.
func LoadParityAllowlist(repoRoot string) (map[string]struct{}, error) {
	path := filepath.Join(repoRoot, OpenAPIDir, ParityAllowlistRel)
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	out := make(map[string]struct{})
	for line := range strings.SplitSeq(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		out[line] = struct{}{}
	}
	return out, nil
}

// AssertCatalogParity fails when routeCatalog routes are missing from the OpenAPI union.
func AssertCatalogParity(repoRoot string) error {
	specRoutes, err := RouteKeysFromSpecUnion(repoRoot)
	if err != nil {
		return err
	}
	allow, err := LoadParityAllowlist(repoRoot)
	if err != nil {
		return err
	}
	var missing []string
	for _, route := range controlplane.Catalog() {
		key := route.Key()
		if _, ok := specRoutes[key]; ok {
			continue
		}
		if _, ok := allow[key]; ok {
			continue
		}
		missing = append(missing, key)
	}
	sort.Strings(missing)
	if len(missing) > 0 {
		return fmt.Errorf("openapi parity: %d catalog route(s) missing from spec (add stub or allowlist): %s",
			len(missing), strings.Join(missing, ", "))
	}
	return nil
}
