USE ad_event_processor;

ALTER TABLE clicks ADD COLUMN IF NOT EXISTS rtt_syn_ms UInt16 DEFAULT 0;
ALTER TABLE clicks ADD COLUMN IF NOT EXISTS ttfb_app_ms UInt16 DEFAULT 0;
ALTER TABLE clicks ADD COLUMN IF NOT EXISTS rtt_split_delta_ms UInt16 DEFAULT 0;

ALTER TABLE conversions ADD COLUMN IF NOT EXISTS rtt_syn_ms UInt16 DEFAULT 0;
ALTER TABLE conversions ADD COLUMN IF NOT EXISTS ttfb_app_ms UInt16 DEFAULT 0;
ALTER TABLE conversions ADD COLUMN IF NOT EXISTS rtt_split_delta_ms UInt16 DEFAULT 0;

ALTER TABLE impressions ADD COLUMN IF NOT EXISTS rtt_syn_ms UInt16 DEFAULT 0;
ALTER TABLE impressions ADD COLUMN IF NOT EXISTS ttfb_app_ms UInt16 DEFAULT 0;
ALTER TABLE impressions ADD COLUMN IF NOT EXISTS rtt_split_delta_ms UInt16 DEFAULT 0;
