// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api/proto/events.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AdEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Metadata      *EventMetadata         `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdEvent) Reset() {
	*x = AdEvent{}
	mi := &file_api_proto_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdEvent) ProtoMessage() {}

func (x *AdEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdEvent.ProtoReflect.Descriptor instead.
func (*AdEvent) Descriptor() ([]byte, []int) {
	return file_api_proto_events_proto_rawDescGZIP(), []int{0}
}

func (x *AdEvent) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *AdEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *AdEvent) GetMetadata() *EventMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EventMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClickId       string                 `protobuf:"bytes,1,opt,name=click_id,json=clickId,proto3" json:"click_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeviceType    string                 `protobuf:"bytes,3,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	Os            string                 `protobuf:"bytes,4,opt,name=os,proto3" json:"os,omitempty"`
	Extra         map[string]string      `protobuf:"bytes,5,rep,name=extra,proto3" json:"extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventMetadata) Reset() {
	*x = EventMetadata{}
	mi := &file_api_proto_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMetadata) ProtoMessage() {}

func (x *EventMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMetadata.ProtoReflect.Descriptor instead.
func (*EventMetadata) Descriptor() ([]byte, []int) {
	return file_api_proto_events_proto_rawDescGZIP(), []int{1}
}

func (x *EventMetadata) GetClickId() string {
	if x != nil {
		return x.ClickId
	}
	return ""
}

func (x *EventMetadata) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EventMetadata) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *EventMetadata) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *EventMetadata) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

type TrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackResponse) Reset() {
	*x = TrackResponse{}
	mi := &file_api_proto_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackResponse) ProtoMessage() {}

func (x *TrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackResponse.ProtoReflect.Descriptor instead.
func (*TrackResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_events_proto_rawDescGZIP(), []int{2}
}

func (x *TrackResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TrackResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_proto_events_proto protoreflect.FileDescriptor

const file_api_proto_events_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/events.proto\x12\x06ads.v1\"|\n" +
	"\aAdEvent\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x121\n" +
	"\bmetadata\x18\x03 \x01(\v2\x15.ads.v1.EventMetadataR\bmetadata\"\xe6\x01\n" +
	"\rEventMetadata\x12\x19\n" +
	"\bclick_id\x18\x01 \x01(\tR\aclickId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1f\n" +
	"\vdevice_type\x18\x03 \x01(\tR\n" +
	"deviceType\x12\x0e\n" +
	"\x02os\x18\x04 \x01(\tR\x02os\x126\n" +
	"\x05extra\x18\x05 \x03(\v2 .ads.v1.EventMetadata.ExtraEntryR\x05extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"F\n" +
	"\rTrackResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06statusB<Z:github.com/mykhailov-ua/ad-event-processor/internal/ads/pbb\x06proto3"

var (
	file_api_proto_events_proto_rawDescOnce sync.Once
	file_api_proto_events_proto_rawDescData []byte
)

func file_api_proto_events_proto_rawDescGZIP() []byte {
	file_api_proto_events_proto_rawDescOnce.Do(func() {
		file_api_proto_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_events_proto_rawDesc), len(file_api_proto_events_proto_rawDesc)))
	})
	return file_api_proto_events_proto_rawDescData
}

var file_api_proto_events_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_events_proto_goTypes = []any{
	(*AdEvent)(nil),       // 0: ads.v1.AdEvent
	(*EventMetadata)(nil), // 1: ads.v1.EventMetadata
	(*TrackResponse)(nil), // 2: ads.v1.TrackResponse
	nil,                   // 3: ads.v1.EventMetadata.ExtraEntry
}
var file_api_proto_events_proto_depIdxs = []int32{
	1, // 0: ads.v1.AdEvent.metadata:type_name -> ads.v1.EventMetadata
	3, // 1: ads.v1.EventMetadata.extra:type_name -> ads.v1.EventMetadata.ExtraEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_events_proto_init() }
func file_api_proto_events_proto_init() {
	if File_api_proto_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_events_proto_rawDesc), len(file_api_proto_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_events_proto_goTypes,
		DependencyIndexes: file_api_proto_events_proto_depIdxs,
		MessageInfos:      file_api_proto_events_proto_msgTypes,
	}.Build()
	File_api_proto_events_proto = out.File
	file_api_proto_events_proto_goTypes = nil
	file_api_proto_events_proto_depIdxs = nil
}
