package installer

import (
	"fmt"
	"path/filepath"

	"github.com/bidshard/ad-event-processor/pkg/branding"
	"github.com/bidshard/ad-event-processor/pkg/platformconfig"
)

const (
	trackerGOGC       = "300"
	trackerGOMEMLIMIT = "700MiB"
	processorGOGC     = "100"
)

func trackerIngressSchema(profile *InstallProfile) string {
	if profile == nil || profile.IngressSchema == "" {
		return platformconfig.IngressAdEventProcessorNative
	}
	return platformconfig.NormalizeIngressSchema(string(profile.IngressSchema))
}

func renderSecrets(profile *InstallProfile) []byte {
	lines := []string{
		"REDIS_URL=redis://localhost:6379",
		"AD_EVENT_PROCESSOR_TELEMETRY_ENABLED=" + boolString(profile.TelemetryEnabled),
		"TRACKER_INGRESS_SCHEMA=" + trackerIngressSchema(profile),
		"GOGC=" + trackerGOGC,
		"GOMEMLIMIT=" + trackerGOMEMLIMIT,
	}
	if profile.Type == ProfileSingleVPS {
		lines = append(lines, "REDIS_ADDRS="+platformconfig.RedisAddrsForProfile(string(profile.Type)))
	}
	return []byte(joinLines(lines))
}

func renderComposeEnv(profile *InstallProfile) []byte {
	lines := []string{
		"# Generated by ad-event-processor-install apply — do not edit by hand",
		"# UDS defaults: DB_DSN host=/run/ad-event-processor/postgresql; REDIS_ADDRS=/run/ad-event-processor/redis/*.sock (see .env.example)",
		"TRACKER_INGRESS_SCHEMA=" + trackerIngressSchema(profile),
		"GOGC=" + trackerGOGC,
		"GOMEMLIMIT=" + trackerGOMEMLIMIT,
		"PROCESSOR_GOGC=" + processorGOGC,
		"REDIS_ADDRS=" + platformconfig.RedisAddrsForProfile(string(profile.Type)),
	}
	return []byte(joinLines(lines))
}

func composeEnvPath() string {
	if root := installRoot(); root != "" {
		return filepath.Join(root, "install.compose.env")
	}
	return filepath.Join(repoRoot(), "install.compose.env")
}

func joinLines(lines []string) string {
	out := ""
	for i, line := range lines {
		if i > 0 {
			out += "\n"
		}
		out += line
	}
	return out + "\n"
}

func applyServiceBinaries(profile *InstallProfile, dryRun bool) error {
	deploys := []struct {
		name   string
		spec   ServiceDeploy
		target string
	}{
		{"tracker", profile.Tracker, "/usr/local/bin/tracker"},
		{"processor", profile.Processor, "/usr/local/bin/processor"},
	}
	for _, d := range deploys {
		if d.spec.Binary == "" {
			continue
		}
		if dryRun {
			fmt.Printf("[Dry-Run] Would deploy %s from %s (health=%s)\n", d.name, d.spec.Binary, d.spec.HealthURL)
			continue
		}
		deploy := &BinaryDeploy{
			Service:    d.name,
			SourcePath: d.spec.Binary,
			TargetPath: d.target,
			HealthURL:  d.spec.HealthURL,
			Version:    d.spec.Version,
		}
		if err := deploy.DeployBinary(); err != nil {
			return fmt.Errorf("%s deploy: %w", d.name, err)
		}
		fmt.Printf("Deployed %s from %s\n", d.name, d.spec.Binary)
	}
	return nil
}

func rollbackUnitPath(service string) string {
	if root := installRoot(); root != "" {
		return filepath.Join(root, "etc/systemd/system", RollbackSystemdUnitPrefix+service+".service")
	}
	return filepath.Join("/etc/systemd/system", RollbackSystemdUnitPrefix+service+".service")
}

func renderRollbackUnit(service string) []byte {
	return []byte(fmt.Sprintf(`[Unit]
Description=%s rollback %s after crash loop
After=network.target

[Service]
Type=oneshot
ExecStart=/usr/local/bin/ad-event-processor-install rollback %s
`, branding.ProductName(), service, service))
}

func writeRollbackUnits(profile *InstallProfile, dryRun bool) error {
	if profile.Type != ProfileSingleVPS {
		return nil
	}
	for _, svc := range []string{"tracker", "processor"} {
		content := renderRollbackUnit(svc)
		path := rollbackUnitPath(svc)
		if dryRun {
			fmt.Printf("[Dry-Run] Would render %s\n", path)
			continue
		}
		if err := writeFile(path, content, 0644); err != nil {
			return err
		}
	}
	return nil
}
