services:
  tracker-0:
    image: ${AD_EVENT_PROCESSOR_APP_IMAGE}
    build: null
  processor:
    image: ${AD_EVENT_PROCESSOR_APP_IMAGE}
    build: null
  control:
    image: ${AD_EVENT_PROCESSOR_APP_IMAGE}
    build: null
