services:
  tracker-0:
    image: ${AD_EVENT_PROCESSOR_APP_IMAGE}
    build: !reset
  processor:
    image: ${AD_EVENT_PROCESSOR_APP_IMAGE}
    build: !reset
  control:
    image: ${AD_EVENT_PROCESSOR_APP_IMAGE}
    build: !reset
