services:
  redis-0-replica:
    image: redis:${REDIS_VERSION}
    env_file:
      - ../../.env
    command:
      - redis-server
      - --port
      - '6379'
      - --requirepass
      - ${REDIS_PASSWORD}
      - --masterauth
      - ${REDIS_PASSWORD}
      - --replicaof
      - redis-0
      - '6379'
      - --tcp-backlog
      - '2048'
    networks:
      - database
    depends_on:
      redis-0:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'redis-cli', '-p', '6379', '-a', '${REDIS_PASSWORD}', 'ping']
      interval: ${HEALTHCHECK_INTERVAL:-5s}
      timeout: ${HEALTHCHECK_TIMEOUT:-5s}
      retries: ${HEALTHCHECK_RETRIES:-5}

  redis-1-replica:
    image: redis:${REDIS_VERSION}
    env_file:
      - ../../.env
    command:
      - redis-server
      - --port
      - '6379'
      - --requirepass
      - ${REDIS_PASSWORD}
      - --masterauth
      - ${REDIS_PASSWORD}
      - --replicaof
      - redis-1
      - '6379'
      - --tcp-backlog
      - '2048'
    networks:
      - database
    depends_on:
      redis-1:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'redis-cli', '-p', '6379', '-a', '${REDIS_PASSWORD}', 'ping']
      interval: ${HEALTHCHECK_INTERVAL:-5s}
      timeout: ${HEALTHCHECK_TIMEOUT:-5s}
      retries: ${HEALTHCHECK_RETRIES:-5}

  redis-2-replica:
    image: redis:${REDIS_VERSION}
    env_file:
      - ../../.env
    command:
      - redis-server
      - --port
      - '6379'
      - --requirepass
      - ${REDIS_PASSWORD}
      - --masterauth
      - ${REDIS_PASSWORD}
      - --replicaof
      - redis-2
      - '6379'
      - --tcp-backlog
      - '2048'
    networks:
      - database
    depends_on:
      redis-2:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'redis-cli', '-p', '6379', '-a', '${REDIS_PASSWORD}', 'ping']
      interval: ${HEALTHCHECK_INTERVAL:-5s}
      timeout: ${HEALTHCHECK_TIMEOUT:-5s}
      retries: ${HEALTHCHECK_RETRIES:-5}

  redis-3-replica:
    image: redis:${REDIS_VERSION}
    env_file:
      - ../../.env
    command:
      - redis-server
      - --port
      - '6379'
      - --requirepass
      - ${REDIS_PASSWORD}
      - --masterauth
      - ${REDIS_PASSWORD}
      - --replicaof
      - redis-3
      - '6379'
      - --tcp-backlog
      - '2048'
    networks:
      - database
    depends_on:
      redis-3:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'redis-cli', '-p', '6379', '-a', '${REDIS_PASSWORD}', 'ping']
      interval: ${HEALTHCHECK_INTERVAL:-5s}
      timeout: ${HEALTHCHECK_TIMEOUT:-5s}
      retries: ${HEALTHCHECK_RETRIES:-5}

  sentinel-0:
    image: redis:${REDIS_VERSION}
    env_file:
      - ../../.env
    entrypoint: ['/bin/sh', '/sentinel-entrypoint.sh']
    volumes:
      - ../redis/sentinel-entrypoint.sh:/sentinel-entrypoint.sh:ro
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_SHARD_COUNT: '4'
    networks:
      - database
    depends_on:
      redis-0:
        condition: service_healthy
      redis-1:
        condition: service_healthy
      redis-2:
        condition: service_healthy
      redis-3:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'redis-cli', '-p', '26379', 'ping']
      interval: ${HEALTHCHECK_INTERVAL:-5s}
      timeout: ${HEALTHCHECK_TIMEOUT:-5s}
      retries: ${HEALTHCHECK_RETRIES:-5}

  sentinel-1:
    image: redis:${REDIS_VERSION}
    env_file:
      - ../../.env
    entrypoint: ['/bin/sh', '/sentinel-entrypoint.sh']
    volumes:
      - ../redis/sentinel-entrypoint.sh:/sentinel-entrypoint.sh:ro
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_SHARD_COUNT: '4'
    networks:
      - database
    depends_on:
      sentinel-0:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'redis-cli', '-p', '26379', 'ping']
      interval: ${HEALTHCHECK_INTERVAL:-5s}
      timeout: ${HEALTHCHECK_TIMEOUT:-5s}
      retries: ${HEALTHCHECK_RETRIES:-5}

  sentinel-2:
    image: redis:${REDIS_VERSION}
    env_file:
      - ../../.env
    entrypoint: ['/bin/sh', '/sentinel-entrypoint.sh']
    volumes:
      - ../redis/sentinel-entrypoint.sh:/sentinel-entrypoint.sh:ro
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_SHARD_COUNT: '4'
    networks:
      - database
    depends_on:
      sentinel-0:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'redis-cli', '-p', '26379', 'ping']
      interval: ${HEALTHCHECK_INTERVAL:-5s}
      timeout: ${HEALTHCHECK_TIMEOUT:-5s}
      retries: ${HEALTHCHECK_RETRIES:-5}
