package openrtb

func Profile() IntegrationProfile {
	return IntegrationProfile{
		OpenRTBVersion: "2.6",
		Required: []string{
			"id",
			"imp[].id",
			"imp[].bidfloor",
			"site|app",
			"device.ip|device.ipv6",
			"device.ua",
		},
		Supported: []string{
			"imp.banner",
			"imp.video",
			"imp.video.mimes",
			"imp.video.minduration",
			"imp.video.maxduration",
			"imp.video.w",
			"imp.video.h",
			"imp.pmp.deals[]",
			"imp.pmp.private",
			"imp.metric[]",
			"imp.metric.type",
			"imp.metric.value",
			"imp.metric.vendor",
			"imp.secure",
			"imp.banner.w",
			"imp.banner.h",
			"site.domain",
			"site.page",
			"site.cat",
			"app.bundle",
			"app.ver",
			"app.cat",
			"device.devicetype",
			"device.os",
			"device.language",
			"device.ifa",
			"device.lmt",
			"device.connectiontype",
			"device.geo.country",
			"device.geo.region",
			"user.id",
			"user.buyeruid",
			"user.ext.eids[]",
			"user.ext.eids[].source",
			"user.ext.eids[].uids[]",
			"source.tid",
			"source.ext.schain",
			"regs.ext.gdpr",
			"regs.ext.us_privacy",
			"regs.coppa",
			"bcat",
			"badv",
			"bapp",
			"bseat",
			"imp.pmp.deals[].wseat",
			"at",
			"cur[]",
			"tmax",
			"test",
			"imp.bidfloorcur",
		},
		NotSupported: []string{
			"dooh",
			"imp.native",
			"imp.audio",
			"podid",
			"slotinpod",
			"device.sua",
			"ads.cert",
			"openrtb 3.0",
			"mid",
		},
	}
}
