#!/usr/bin/env bash

load_test_env_file() {
  local root="${1:-${ROOT:-}}"
  if [[ -z "$root" ]]; then
    root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
  fi
  printf '%s/.env.load-test' "$root"
}

load_test_source_env() {
  local env_file
  env_file="$(load_test_env_file "${1:-}")"
  if [[ ! -f "$env_file" ]]; then
    printf 'load-test-env: ERROR: missing %s\n' "$env_file" >&2
    return 1
  fi
  set -a
  # shellcheck disable=SC1090
  source "$env_file"
  set +a
}

load_test_tracker_ingest_port() {
  local idx="${1:?tracker index}"
  echo $((LOAD_TEST_TRACKER_INGEST_BASE + idx * LOAD_TEST_TRACKER_INGEST_STEP))
}

load_test_tracker_metrics_port() {
  local idx="${1:?tracker index}"
  echo $((LOAD_TEST_TRACKER_METRICS_BASE + idx * LOAD_TEST_TRACKER_METRICS_STEP))
}

load_test_redis_port() {
  local shard="${1:?redis shard index}"
  echo $((LOAD_TEST_REDIS_BASE + shard * LOAD_TEST_REDIS_STEP))
}

load_test_redis_tcp_addrs() {
  local i addrs=""
  for ((i = 0; i < LOAD_TEST_REDIS_SHARDS; i++)); do
    [[ -n "$addrs" ]] && addrs+=","
    addrs+="127.0.0.1:$(load_test_redis_port "$i")"
  done
  printf '%s' "$addrs"
}

load_test_redis_uds_addrs() {
  local i addrs=""
  for ((i = 0; i < LOAD_TEST_REDIS_SHARDS; i++)); do
    [[ -n "$addrs" ]] && addrs+=","
    addrs+="/run/ad-event-processor/redis/redis-${i}.sock"
  done
  printf '%s' "$addrs"
}

load_test_redis_addrs() {
  if [[ "${LOAD_TEST_REDIS_USE_UDS:-${LOAD_TEST_TRANSPORT_USE_UDS:-0}}" == "1" ]]; then
    load_test_redis_uds_addrs
  else
    load_test_redis_tcp_addrs
  fi
}

load_test_export_tracker_ports() {
  local i ingest metrics
  for ((i = 0; i < LOAD_TEST_TRACKER_COUNT; i++)); do
    ingest="$(load_test_tracker_ingest_port "$i")"
    metrics="$(load_test_tracker_metrics_port "$i")"
    export "LOAD_TEST_TRACKER_${i}_INGEST_PORT=${ingest}"
    export "LOAD_TEST_TRACKER_${i}_METRICS_PORT=${metrics}"
    export "LOAD_TEST_TRACKER_${i}_HEALTH_URL=http://127.0.0.1:${ingest}/health"
  done
}

load_test_export_derived() {
  local i
  export LOAD_TEST_REDIS_USE_UDS="${LOAD_TEST_REDIS_USE_UDS:-${LOAD_TEST_TRANSPORT_USE_UDS:-0}}"
  export LOAD_TEST_REDIS_ADDRS="$(load_test_redis_addrs)"
  export LOAD_TEST_REDIS_PORT="$(load_test_redis_port 0)"
  export LOAD_TEST_EDGE_URL="http://127.0.0.1:${LOAD_TEST_EDGE_PORT}"
  export LOAD_TEST_PROMETHEUS_URL="http://127.0.0.1:${LOAD_TEST_PROMETHEUS_PORT}"
  export LOAD_TEST_CONTROL_URL="http://127.0.0.1:${LOAD_TEST_CONTROL_PORT}"
  load_test_export_tracker_ports
  export LOAD_TEST_TRACKER_BASES_CSV="$(load_test_tracker_bases_csv "${LOAD_TEST_TRACKER_COUNT}")"
  export LOAD_TEST_CONSTRAINED_TRACKER_BASES_CSV="$(load_test_tracker_bases_csv "${LOAD_TEST_CONSTRAINED_TRACKERS}")"
  export LOAD_TEST_CONSTRAINED_METRICS_PORTS=""
  for ((i = 0; i < LOAD_TEST_CONSTRAINED_TRACKERS; i++)); do
    [[ -n "$LOAD_TEST_CONSTRAINED_METRICS_PORTS" ]] && LOAD_TEST_CONSTRAINED_METRICS_PORTS+=","
    LOAD_TEST_CONSTRAINED_METRICS_PORTS+="127.0.0.1:$(load_test_tracker_metrics_port "$i")"
  done
  export LOAD_TEST_CONSTRAINED_METRICS_PORTS
  export LOAD_TEST_ALL_INGEST_PORTS=""
  for ((i = 0; i < LOAD_TEST_TRACKER_COUNT; i++)); do
    [[ -n "$LOAD_TEST_ALL_INGEST_PORTS" ]] && LOAD_TEST_ALL_INGEST_PORTS+=" "
    LOAD_TEST_ALL_INGEST_PORTS+="$(load_test_tracker_ingest_port "$i")"
  done
  export LOAD_TEST_ALL_INGEST_PORTS
}

load_test_tracker_bases_csv() {
  local count="${1:?count}"
  local i first=1 base
  for ((i = 0; i < count; i++)); do
    base="http://127.0.0.1:$(load_test_tracker_ingest_port "$i")"
    if [[ "$first" -eq 1 ]]; then
      printf '%s' "$base"
      first=0
    else
      printf ',%s' "$base"
    fi
  done
}

load_test_constrained_ingest_ports() {
  local i
  for ((i = 0; i < LOAD_TEST_CONSTRAINED_TRACKERS; i++)); do
    load_test_tracker_ingest_port "$i"
  done
}

load_test_materialize_runtime_env() {
  local root="${1:-${ROOT:-}}"
  local out i ingest metrics
  out="$(load_test_runtime_env_path "$root")"
  mkdir -p "$(dirname "$out")"
  load_test_source_env "$root" || return 1
  load_test_export_derived
  {
    printf '# Generated by scripts/lib/load_test_env.sh - do not edit.\n'
    printf 'LOAD_TEST_REDIS_USE_UDS=%s\n' "${LOAD_TEST_REDIS_USE_UDS:-${LOAD_TEST_TRANSPORT_USE_UDS:-0}}"
    printf 'LOAD_TEST_REDIS_ADDRS=%s\n' "$LOAD_TEST_REDIS_ADDRS"
    printf 'REDIS_ADDRS=%s\n' "$LOAD_TEST_REDIS_ADDRS"
    printf 'LOAD_TEST_REDIS_PORT=%s\n' "$LOAD_TEST_REDIS_PORT"
    printf 'LOAD_TEST_EDGE_URL=%s\n' "$LOAD_TEST_EDGE_URL"
    printf 'LOAD_TEST_PROMETHEUS_URL=%s\n' "$LOAD_TEST_PROMETHEUS_URL"
    printf 'LOAD_TEST_CONTROL_URL=%s\n' "$LOAD_TEST_CONTROL_URL"
    printf 'LOAD_TEST_TRACKER_BASES_CSV=%s\n' "$LOAD_TEST_TRACKER_BASES_CSV"
    printf 'LOAD_TEST_CONSTRAINED_TRACKER_BASES_CSV=%s\n' "$LOAD_TEST_CONSTRAINED_TRACKER_BASES_CSV"
    printf 'LOAD_TEST_CONSTRAINED_METRICS_PORTS=%s\n' "$LOAD_TEST_CONSTRAINED_METRICS_PORTS"
    for ((i = 0; i < LOAD_TEST_TRACKER_COUNT; i++)); do
      ingest="$(load_test_tracker_ingest_port "$i")"
      metrics="$(load_test_tracker_metrics_port "$i")"
      printf 'LOAD_TEST_TRACKER_%s_INGEST_PORT=%s\n' "$i" "$ingest"
      printf 'LOAD_TEST_TRACKER_%s_METRICS_PORT=%s\n' "$i" "$metrics"
      printf 'LOAD_TEST_TRACKER_%s_HEALTH_URL=%s\n' "$i" "http://127.0.0.1:${ingest}/health"
    done
    for ((i = 0; i < LOAD_TEST_REDIS_SHARDS; i++)); do
      printf 'LOAD_TEST_REDIS_%s_PORT=%s\n' "$i" "$(load_test_redis_port "$i")"
    done
  } > "$out"
  printf '%s\n' "$out"
}

load_test_runtime_env_path() {
  local root="${1:-${ROOT:-}}"
  if [[ -z "$root" ]]; then
    root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
  fi
  printf '%s/deploy/compose/.env.load-test.runtime' "$root"
}

load_test_compose_env_files() {
  local root="${1:-${ROOT:-}}"
  load_test_materialize_runtime_env "$root" > /dev/null
  if [[ -f "$root/.env" ]]; then
    printf '%s\n%s\n%s\n' "$root/.env" "$(load_test_env_file "$root")" "$(load_test_runtime_env_path "$root")"
  else
    printf '%s\n%s\n' "$(load_test_env_file "$root")" "$(load_test_runtime_env_path "$root")"
  fi
}

load_test_compose_env_args() {
  local root="${1:-${ROOT:-}}" file
  while IFS= read -r file; do
    printf -- '--env-file=%s\n' "$file"
  done < <(load_test_compose_env_files "$root")
}

load_test_bootstrap() {
  local root="${1:-${ROOT:-}}"
  load_test_source_env "$root" || return 1
  load_test_export_derived
  load_test_materialize_runtime_env "$root" > /dev/null
}

load_test_constrained_tracker_bases_csv() {
  load_test_tracker_bases_csv "${LOAD_TEST_CONSTRAINED_TRACKERS}"
}

load_test_compose() {
  local -n _out=$1
  local root="${2:-${ROOT:-}}"
  load_test_bootstrap "$root"
  bash "$(dirname "${BASH_SOURCE[0]}")/render_load_test_config.sh"
  _out=(docker compose --profile analytics_ml --profile monitoring --profile resilience)
  local file
  while IFS= read -r file; do
    _out+=(--env-file="$file")
  done < <(load_test_compose_env_files "$root")
  _out+=(-f docker-compose.yaml -f docker-compose.load-test.yaml)
}
