_AD_EVENT_PROCESSOR_SCRIPTS="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AD_EVENT_PROCESSOR_SCRIPTS_ROOT="$_AD_EVENT_PROCESSOR_SCRIPTS"
AD_EVENT_PROCESSOR_REPO_ROOT="$(cd "$AD_EVENT_PROCESSOR_SCRIPTS_ROOT/.." && pwd)"
ROOT="$AD_EVENT_PROCESSOR_REPO_ROOT"
SCRIPTS="$AD_EVENT_PROCESSOR_SCRIPTS_ROOT"
export ROOT SCRIPTS AD_EVENT_PROCESSOR_SCRIPTS_ROOT AD_EVENT_PROCESSOR_REPO_ROOT

source "$AD_EVENT_PROCESSOR_SCRIPTS_ROOT/lib/safe_paths.sh"
source "$AD_EVENT_PROCESSOR_SCRIPTS_ROOT/lib/ci_artifacts.sh"
