_ESPX_SCRIPTS="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ESPX_SCRIPTS_ROOT="$_ESPX_SCRIPTS"
ESPX_REPO_ROOT="$(cd "$ESPX_SCRIPTS_ROOT/.." && pwd)"
ROOT="$ESPX_REPO_ROOT"
SCRIPTS="$ESPX_SCRIPTS_ROOT"
export ROOT SCRIPTS ESPX_SCRIPTS_ROOT ESPX_REPO_ROOT

source "$ESPX_SCRIPTS_ROOT/lib/safe_paths.sh"
