// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: outbox.proto

package outboxpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CampaignPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	BudgetLimit   int64                  `protobuf:"varint,2,opt,name=budget_limit,json=budgetLimit,proto3" json:"budget_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignPayload) Reset() {
	*x = CampaignPayload{}
	mi := &file_outbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignPayload) ProtoMessage() {}

func (x *CampaignPayload) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignPayload.ProtoReflect.Descriptor instead.
func (*CampaignPayload) Descriptor() ([]byte, []int) {
	return file_outbox_proto_rawDescGZIP(), []int{0}
}

func (x *CampaignPayload) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *CampaignPayload) GetBudgetLimit() int64 {
	if x != nil {
		return x.BudgetLimit
	}
	return 0
}

type CampaignIdPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignIdPayload) Reset() {
	*x = CampaignIdPayload{}
	mi := &file_outbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignIdPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignIdPayload) ProtoMessage() {}

func (x *CampaignIdPayload) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignIdPayload.ProtoReflect.Descriptor instead.
func (*CampaignIdPayload) Descriptor() ([]byte, []int) {
	return file_outbox_proto_rawDescGZIP(), []int{1}
}

func (x *CampaignIdPayload) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

type BrandIdPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrandId       string                 `protobuf:"bytes,1,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrandIdPayload) Reset() {
	*x = BrandIdPayload{}
	mi := &file_outbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandIdPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandIdPayload) ProtoMessage() {}

func (x *BrandIdPayload) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandIdPayload.ProtoReflect.Descriptor instead.
func (*BrandIdPayload) Descriptor() ([]byte, []int) {
	return file_outbox_proto_rawDescGZIP(), []int{2}
}

func (x *BrandIdPayload) GetBrandId() string {
	if x != nil {
		return x.BrandId
	}
	return ""
}

type BrandFcapPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BrandId       string                 `protobuf:"bytes,1,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	FreqLimit     int32                  `protobuf:"varint,2,opt,name=freq_limit,json=freqLimit,proto3" json:"freq_limit,omitempty"`
	FreqWindow    int32                  `protobuf:"varint,3,opt,name=freq_window,json=freqWindow,proto3" json:"freq_window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrandFcapPayload) Reset() {
	*x = BrandFcapPayload{}
	mi := &file_outbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandFcapPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandFcapPayload) ProtoMessage() {}

func (x *BrandFcapPayload) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandFcapPayload.ProtoReflect.Descriptor instead.
func (*BrandFcapPayload) Descriptor() ([]byte, []int) {
	return file_outbox_proto_rawDescGZIP(), []int{3}
}

func (x *BrandFcapPayload) GetBrandId() string {
	if x != nil {
		return x.BrandId
	}
	return ""
}

func (x *BrandFcapPayload) GetFreqLimit() int32 {
	if x != nil {
		return x.FreqLimit
	}
	return 0
}

func (x *BrandFcapPayload) GetFreqWindow() int32 {
	if x != nil {
		return x.FreqWindow
	}
	return 0
}

type CampaignSchedulePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	StartAtUnix   int64                  `protobuf:"varint,2,opt,name=start_at_unix,json=startAtUnix,proto3" json:"start_at_unix,omitempty"`
	EndAtUnix     int64                  `protobuf:"varint,3,opt,name=end_at_unix,json=endAtUnix,proto3" json:"end_at_unix,omitempty"`
	DaypartHours  []int32                `protobuf:"varint,4,rep,packed,name=daypart_hours,json=daypartHours,proto3" json:"daypart_hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignSchedulePayload) Reset() {
	*x = CampaignSchedulePayload{}
	mi := &file_outbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignSchedulePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignSchedulePayload) ProtoMessage() {}

func (x *CampaignSchedulePayload) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignSchedulePayload.ProtoReflect.Descriptor instead.
func (*CampaignSchedulePayload) Descriptor() ([]byte, []int) {
	return file_outbox_proto_rawDescGZIP(), []int{4}
}

func (x *CampaignSchedulePayload) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *CampaignSchedulePayload) GetStartAtUnix() int64 {
	if x != nil {
		return x.StartAtUnix
	}
	return 0
}

func (x *CampaignSchedulePayload) GetEndAtUnix() int64 {
	if x != nil {
		return x.EndAtUnix
	}
	return 0
}

func (x *CampaignSchedulePayload) GetDaypartHours() []int32 {
	if x != nil {
		return x.DaypartHours
	}
	return nil
}

type CampaignPacingPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	PacingMode    string                 `protobuf:"bytes,2,opt,name=pacing_mode,json=pacingMode,proto3" json:"pacing_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignPacingPayload) Reset() {
	*x = CampaignPacingPayload{}
	mi := &file_outbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignPacingPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignPacingPayload) ProtoMessage() {}

func (x *CampaignPacingPayload) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignPacingPayload.ProtoReflect.Descriptor instead.
func (*CampaignPacingPayload) Descriptor() ([]byte, []int) {
	return file_outbox_proto_rawDescGZIP(), []int{5}
}

func (x *CampaignPacingPayload) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *CampaignPacingPayload) GetPacingMode() string {
	if x != nil {
		return x.PacingMode
	}
	return ""
}

type SettingsPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      map[string]string      `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingsPayload) Reset() {
	*x = SettingsPayload{}
	mi := &file_outbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsPayload) ProtoMessage() {}

func (x *SettingsPayload) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsPayload.ProtoReflect.Descriptor instead.
func (*SettingsPayload) Descriptor() ([]byte, []int) {
	return file_outbox_proto_rawDescGZIP(), []int{6}
}

func (x *SettingsPayload) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

type BlacklistPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlacklistPayload) Reset() {
	*x = BlacklistPayload{}
	mi := &file_outbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlacklistPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlacklistPayload) ProtoMessage() {}

func (x *BlacklistPayload) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlacklistPayload.ProtoReflect.Descriptor instead.
func (*BlacklistPayload) Descriptor() ([]byte, []int) {
	return file_outbox_proto_rawDescGZIP(), []int{7}
}

func (x *BlacklistPayload) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *BlacklistPayload) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *BlacklistPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type FraudThreatPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	CampaignId    string                 `protobuf:"bytes,3,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	Boost         int32                  `protobuf:"varint,5,opt,name=boost,proto3" json:"boost,omitempty"`
	TtlSeconds    int64                  `protobuf:"varint,6,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FraudThreatPayload) Reset() {
	*x = FraudThreatPayload{}
	mi := &file_outbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudThreatPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudThreatPayload) ProtoMessage() {}

func (x *FraudThreatPayload) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudThreatPayload.ProtoReflect.Descriptor instead.
func (*FraudThreatPayload) Descriptor() ([]byte, []int) {
	return file_outbox_proto_rawDescGZIP(), []int{8}
}

func (x *FraudThreatPayload) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *FraudThreatPayload) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *FraudThreatPayload) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *FraudThreatPayload) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *FraudThreatPayload) GetBoost() int32 {
	if x != nil {
		return x.Boost
	}
	return 0
}

func (x *FraudThreatPayload) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type FraudModelVersionPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelVersion  string                 `protobuf:"bytes,1,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	ShardId       int32                  `protobuf:"varint,3,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FraudModelVersionPayload) Reset() {
	*x = FraudModelVersionPayload{}
	mi := &file_outbox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FraudModelVersionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FraudModelVersionPayload) ProtoMessage() {}

func (x *FraudModelVersionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FraudModelVersionPayload.ProtoReflect.Descriptor instead.
func (*FraudModelVersionPayload) Descriptor() ([]byte, []int) {
	return file_outbox_proto_rawDescGZIP(), []int{9}
}

func (x *FraudModelVersionPayload) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *FraudModelVersionPayload) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *FraudModelVersionPayload) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

type UserConsentPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIdHash    string                 `protobuf:"bytes,1,opt,name=user_id_hash,json=userIdHash,proto3" json:"user_id_hash,omitempty"`
	Purposes      int32                  `protobuf:"varint,2,opt,name=purposes,proto3" json:"purposes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserConsentPayload) Reset() {
	*x = UserConsentPayload{}
	mi := &file_outbox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserConsentPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserConsentPayload) ProtoMessage() {}

func (x *UserConsentPayload) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserConsentPayload.ProtoReflect.Descriptor instead.
func (*UserConsentPayload) Descriptor() ([]byte, []int) {
	return file_outbox_proto_rawDescGZIP(), []int{10}
}

func (x *UserConsentPayload) GetUserIdHash() string {
	if x != nil {
		return x.UserIdHash
	}
	return ""
}

func (x *UserConsentPayload) GetPurposes() int32 {
	if x != nil {
		return x.Purposes
	}
	return 0
}

type PurgeUserDataPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErasureId     string                 `protobuf:"bytes,1,opt,name=erasure_id,json=erasureId,proto3" json:"erasure_id,omitempty"`
	UserIdHash    string                 `protobuf:"bytes,2,opt,name=user_id_hash,json=userIdHash,proto3" json:"user_id_hash,omitempty"`
	SubjectUserId string                 `protobuf:"bytes,3,opt,name=subject_user_id,json=subjectUserId,proto3" json:"subject_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PurgeUserDataPayload) Reset() {
	*x = PurgeUserDataPayload{}
	mi := &file_outbox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurgeUserDataPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurgeUserDataPayload) ProtoMessage() {}

func (x *PurgeUserDataPayload) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurgeUserDataPayload.ProtoReflect.Descriptor instead.
func (*PurgeUserDataPayload) Descriptor() ([]byte, []int) {
	return file_outbox_proto_rawDescGZIP(), []int{11}
}

func (x *PurgeUserDataPayload) GetErasureId() string {
	if x != nil {
		return x.ErasureId
	}
	return ""
}

func (x *PurgeUserDataPayload) GetUserIdHash() string {
	if x != nil {
		return x.UserIdHash
	}
	return ""
}

func (x *PurgeUserDataPayload) GetSubjectUserId() string {
	if x != nil {
		return x.SubjectUserId
	}
	return ""
}

type PausePlacementPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	PlacementId   string                 `protobuf:"bytes,2,opt,name=placement_id,json=placementId,proto3" json:"placement_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PausePlacementPayload) Reset() {
	*x = PausePlacementPayload{}
	mi := &file_outbox_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PausePlacementPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PausePlacementPayload) ProtoMessage() {}

func (x *PausePlacementPayload) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PausePlacementPayload.ProtoReflect.Descriptor instead.
func (*PausePlacementPayload) Descriptor() ([]byte, []int) {
	return file_outbox_proto_rawDescGZIP(), []int{12}
}

func (x *PausePlacementPayload) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *PausePlacementPayload) GetPlacementId() string {
	if x != nil {
		return x.PlacementId
	}
	return ""
}

func (x *PausePlacementPayload) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type QuotaRepairPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	ShardId       int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	PgReserved    int64                  `protobuf:"varint,4,opt,name=pg_reserved,json=pgReserved,proto3" json:"pg_reserved,omitempty"`
	RedisExpected int64                  `protobuf:"varint,5,opt,name=redis_expected,json=redisExpected,proto3" json:"redis_expected,omitempty"`
	ChunkSize     int64                  `protobuf:"varint,6,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	DriftMicro    int64                  `protobuf:"varint,7,opt,name=drift_micro,json=driftMicro,proto3" json:"drift_micro,omitempty"`
	RepairMicro   int64                  `protobuf:"varint,8,opt,name=repair_micro,json=repairMicro,proto3" json:"repair_micro,omitempty"`
	Reason        string                 `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuotaRepairPayload) Reset() {
	*x = QuotaRepairPayload{}
	mi := &file_outbox_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaRepairPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaRepairPayload) ProtoMessage() {}

func (x *QuotaRepairPayload) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaRepairPayload.ProtoReflect.Descriptor instead.
func (*QuotaRepairPayload) Descriptor() ([]byte, []int) {
	return file_outbox_proto_rawDescGZIP(), []int{13}
}

func (x *QuotaRepairPayload) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *QuotaRepairPayload) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *QuotaRepairPayload) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *QuotaRepairPayload) GetPgReserved() int64 {
	if x != nil {
		return x.PgReserved
	}
	return 0
}

func (x *QuotaRepairPayload) GetRedisExpected() int64 {
	if x != nil {
		return x.RedisExpected
	}
	return 0
}

func (x *QuotaRepairPayload) GetChunkSize() int64 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *QuotaRepairPayload) GetDriftMicro() int64 {
	if x != nil {
		return x.DriftMicro
	}
	return 0
}

func (x *QuotaRepairPayload) GetRepairMicro() int64 {
	if x != nil {
		return x.RepairMicro
	}
	return 0
}

func (x *QuotaRepairPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ReconciliationAdjustPayload struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RunId             int64                  `protobuf:"varint,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	CampaignId        string                 `protobuf:"bytes,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	CustomerId        string                 `protobuf:"bytes,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	ShardId           int32                  `protobuf:"varint,4,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	LedgerAmountMicro int64                  `protobuf:"varint,5,opt,name=ledger_amount_micro,json=ledgerAmountMicro,proto3" json:"ledger_amount_micro,omitempty"`
	RedisDeltaMicro   int64                  `protobuf:"varint,6,opt,name=redis_delta_micro,json=redisDeltaMicro,proto3" json:"redis_delta_micro,omitempty"`
	Reason            string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReconciliationAdjustPayload) Reset() {
	*x = ReconciliationAdjustPayload{}
	mi := &file_outbox_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconciliationAdjustPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconciliationAdjustPayload) ProtoMessage() {}

func (x *ReconciliationAdjustPayload) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconciliationAdjustPayload.ProtoReflect.Descriptor instead.
func (*ReconciliationAdjustPayload) Descriptor() ([]byte, []int) {
	return file_outbox_proto_rawDescGZIP(), []int{14}
}

func (x *ReconciliationAdjustPayload) GetRunId() int64 {
	if x != nil {
		return x.RunId
	}
	return 0
}

func (x *ReconciliationAdjustPayload) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *ReconciliationAdjustPayload) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ReconciliationAdjustPayload) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *ReconciliationAdjustPayload) GetLedgerAmountMicro() int64 {
	if x != nil {
		return x.LedgerAmountMicro
	}
	return 0
}

func (x *ReconciliationAdjustPayload) GetRedisDeltaMicro() int64 {
	if x != nil {
		return x.RedisDeltaMicro
	}
	return 0
}

func (x *ReconciliationAdjustPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SupplyFilesPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trigger       string                 `protobuf:"bytes,1,opt,name=trigger,proto3" json:"trigger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SupplyFilesPayload) Reset() {
	*x = SupplyFilesPayload{}
	mi := &file_outbox_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupplyFilesPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupplyFilesPayload) ProtoMessage() {}

func (x *SupplyFilesPayload) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupplyFilesPayload.ProtoReflect.Descriptor instead.
func (*SupplyFilesPayload) Descriptor() ([]byte, []int) {
	return file_outbox_proto_rawDescGZIP(), []int{15}
}

func (x *SupplyFilesPayload) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

type RtbCatalogReloadPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trigger       string                 `protobuf:"bytes,1,opt,name=trigger,proto3" json:"trigger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RtbCatalogReloadPayload) Reset() {
	*x = RtbCatalogReloadPayload{}
	mi := &file_outbox_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RtbCatalogReloadPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RtbCatalogReloadPayload) ProtoMessage() {}

func (x *RtbCatalogReloadPayload) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RtbCatalogReloadPayload.ProtoReflect.Descriptor instead.
func (*RtbCatalogReloadPayload) Descriptor() ([]byte, []int) {
	return file_outbox_proto_rawDescGZIP(), []int{16}
}

func (x *RtbCatalogReloadPayload) GetTrigger() string {
	if x != nil {
		return x.Trigger
	}
	return ""
}

type CohortSnapshotPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CohortSnapshotPayload) Reset() {
	*x = CohortSnapshotPayload{}
	mi := &file_outbox_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CohortSnapshotPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CohortSnapshotPayload) ProtoMessage() {}

func (x *CohortSnapshotPayload) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CohortSnapshotPayload.ProtoReflect.Descriptor instead.
func (*CohortSnapshotPayload) Descriptor() ([]byte, []int) {
	return file_outbox_proto_rawDescGZIP(), []int{17}
}

func (x *CohortSnapshotPayload) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type CtvGtaxSettlementPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SettlementId  string                 `protobuf:"bytes,1,opt,name=settlement_id,json=settlementId,proto3" json:"settlement_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CampaignId    string                 `protobuf:"bytes,3,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	SpendMicro    int64                  `protobuf:"varint,4,opt,name=spend_micro,json=spendMicro,proto3" json:"spend_micro,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CtvGtaxSettlementPayload) Reset() {
	*x = CtvGtaxSettlementPayload{}
	mi := &file_outbox_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CtvGtaxSettlementPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CtvGtaxSettlementPayload) ProtoMessage() {}

func (x *CtvGtaxSettlementPayload) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CtvGtaxSettlementPayload.ProtoReflect.Descriptor instead.
func (*CtvGtaxSettlementPayload) Descriptor() ([]byte, []int) {
	return file_outbox_proto_rawDescGZIP(), []int{18}
}

func (x *CtvGtaxSettlementPayload) GetSettlementId() string {
	if x != nil {
		return x.SettlementId
	}
	return ""
}

func (x *CtvGtaxSettlementPayload) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CtvGtaxSettlementPayload) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *CtvGtaxSettlementPayload) GetSpendMicro() int64 {
	if x != nil {
		return x.SpendMicro
	}
	return 0
}

type TelegramEventPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    []byte                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	BotId         int64                  `protobuf:"varint,2,opt,name=bot_id,json=botId,proto3" json:"bot_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelegramEventPayload) Reset() {
	*x = TelegramEventPayload{}
	mi := &file_outbox_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelegramEventPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramEventPayload) ProtoMessage() {}

func (x *TelegramEventPayload) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramEventPayload.ProtoReflect.Descriptor instead.
func (*TelegramEventPayload) Descriptor() ([]byte, []int) {
	return file_outbox_proto_rawDescGZIP(), []int{19}
}

func (x *TelegramEventPayload) GetCampaignId() []byte {
	if x != nil {
		return x.CampaignId
	}
	return nil
}

func (x *TelegramEventPayload) GetBotId() int64 {
	if x != nil {
		return x.BotId
	}
	return 0
}

func (x *TelegramEventPayload) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type SettleBalancePayload struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CustomerId           string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	AmountMicro          int64                  `protobuf:"varint,2,opt,name=amount_micro,json=amountMicro,proto3" json:"amount_micro,omitempty"`
	LedgerIdempotencyKey string                 `protobuf:"bytes,3,opt,name=ledger_idempotency_key,json=ledgerIdempotencyKey,proto3" json:"ledger_idempotency_key,omitempty"`
	PaymentIntentId      string                 `protobuf:"bytes,4,opt,name=payment_intent_id,json=paymentIntentId,proto3" json:"payment_intent_id,omitempty"`
	Provider             string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	ProviderRef          string                 `protobuf:"bytes,6,opt,name=provider_ref,json=providerRef,proto3" json:"provider_ref,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SettleBalancePayload) Reset() {
	*x = SettleBalancePayload{}
	mi := &file_outbox_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettleBalancePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettleBalancePayload) ProtoMessage() {}

func (x *SettleBalancePayload) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettleBalancePayload.ProtoReflect.Descriptor instead.
func (*SettleBalancePayload) Descriptor() ([]byte, []int) {
	return file_outbox_proto_rawDescGZIP(), []int{20}
}

func (x *SettleBalancePayload) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *SettleBalancePayload) GetAmountMicro() int64 {
	if x != nil {
		return x.AmountMicro
	}
	return 0
}

func (x *SettleBalancePayload) GetLedgerIdempotencyKey() string {
	if x != nil {
		return x.LedgerIdempotencyKey
	}
	return ""
}

func (x *SettleBalancePayload) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

func (x *SettleBalancePayload) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SettleBalancePayload) GetProviderRef() string {
	if x != nil {
		return x.ProviderRef
	}
	return ""
}

type ChargebackPayload struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PaymentIntentId   string                 `protobuf:"bytes,1,opt,name=payment_intent_id,json=paymentIntentId,proto3" json:"payment_intent_id,omitempty"`
	CustomerId        string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	AmountMicro       int64                  `protobuf:"varint,3,opt,name=amount_micro,json=amountMicro,proto3" json:"amount_micro,omitempty"`
	ProviderDisputeId string                 `protobuf:"bytes,4,opt,name=provider_dispute_id,json=providerDisputeId,proto3" json:"provider_dispute_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChargebackPayload) Reset() {
	*x = ChargebackPayload{}
	mi := &file_outbox_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChargebackPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargebackPayload) ProtoMessage() {}

func (x *ChargebackPayload) ProtoReflect() protoreflect.Message {
	mi := &file_outbox_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargebackPayload.ProtoReflect.Descriptor instead.
func (*ChargebackPayload) Descriptor() ([]byte, []int) {
	return file_outbox_proto_rawDescGZIP(), []int{21}
}

func (x *ChargebackPayload) GetPaymentIntentId() string {
	if x != nil {
		return x.PaymentIntentId
	}
	return ""
}

func (x *ChargebackPayload) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *ChargebackPayload) GetAmountMicro() int64 {
	if x != nil {
		return x.AmountMicro
	}
	return 0
}

func (x *ChargebackPayload) GetProviderDisputeId() string {
	if x != nil {
		return x.ProviderDisputeId
	}
	return ""
}

var File_outbox_proto protoreflect.FileDescriptor

const file_outbox_proto_rawDesc = "" +
	"\n" +
	"\foutbox.proto\x12\vcoldpath.v1\"U\n" +
	"\x0fCampaignPayload\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12!\n" +
	"\fbudget_limit\x18\x02 \x01(\x03R\vbudgetLimit\"4\n" +
	"\x11CampaignIdPayload\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\"+\n" +
	"\x0eBrandIdPayload\x12\x19\n" +
	"\bbrand_id\x18\x01 \x01(\tR\abrandId\"m\n" +
	"\x10BrandFcapPayload\x12\x19\n" +
	"\bbrand_id\x18\x01 \x01(\tR\abrandId\x12\x1d\n" +
	"\n" +
	"freq_limit\x18\x02 \x01(\x05R\tfreqLimit\x12\x1f\n" +
	"\vfreq_window\x18\x03 \x01(\x05R\n" +
	"freqWindow\"\xa3\x01\n" +
	"\x17CampaignSchedulePayload\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12\"\n" +
	"\rstart_at_unix\x18\x02 \x01(\x03R\vstartAtUnix\x12\x1e\n" +
	"\vend_at_unix\x18\x03 \x01(\x03R\tendAtUnix\x12#\n" +
	"\rdaypart_hours\x18\x04 \x03(\x05R\fdaypartHours\"Y\n" +
	"\x15CampaignPacingPayload\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12\x1f\n" +
	"\vpacing_mode\x18\x02 \x01(\tR\n" +
	"pacingMode\"\x96\x01\n" +
	"\x0fSettingsPayload\x12F\n" +
	"\bsettings\x18\x01 \x03(\v2*.coldpath.v1.SettingsPayload.SettingsEntryR\bsettings\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x10BlacklistPayload\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\xaa\x01\n" +
	"\x12FraudThreatPayload\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x1f\n" +
	"\vcampaign_id\x18\x03 \x01(\tR\n" +
	"campaignId\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12\x14\n" +
	"\x05boost\x18\x05 \x01(\x05R\x05boost\x12\x1f\n" +
	"\vttl_seconds\x18\x06 \x01(\x03R\n" +
	"ttlSeconds\"n\n" +
	"\x18FraudModelVersionPayload\x12#\n" +
	"\rmodel_version\x18\x01 \x01(\tR\fmodelVersion\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12\x19\n" +
	"\bshard_id\x18\x03 \x01(\x05R\ashardId\"R\n" +
	"\x12UserConsentPayload\x12 \n" +
	"\fuser_id_hash\x18\x01 \x01(\tR\n" +
	"userIdHash\x12\x1a\n" +
	"\bpurposes\x18\x02 \x01(\x05R\bpurposes\"\x7f\n" +
	"\x14PurgeUserDataPayload\x12\x1d\n" +
	"\n" +
	"erasure_id\x18\x01 \x01(\tR\terasureId\x12 \n" +
	"\fuser_id_hash\x18\x02 \x01(\tR\n" +
	"userIdHash\x12&\n" +
	"\x0fsubject_user_id\x18\x03 \x01(\tR\rsubjectUserId\"s\n" +
	"\x15PausePlacementPayload\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12!\n" +
	"\fplacement_id\x18\x02 \x01(\tR\vplacementId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"\xab\x02\n" +
	"\x12QuotaRepairPayload\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x05R\ashardId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x1f\n" +
	"\vpg_reserved\x18\x04 \x01(\x03R\n" +
	"pgReserved\x12%\n" +
	"\x0eredis_expected\x18\x05 \x01(\x03R\rredisExpected\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x06 \x01(\x03R\tchunkSize\x12\x1f\n" +
	"\vdrift_micro\x18\a \x01(\x03R\n" +
	"driftMicro\x12!\n" +
	"\frepair_micro\x18\b \x01(\x03R\vrepairMicro\x12\x16\n" +
	"\x06reason\x18\t \x01(\tR\x06reason\"\x85\x02\n" +
	"\x1bReconciliationAdjustPayload\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\x03R\x05runId\x12\x1f\n" +
	"\vcampaign_id\x18\x02 \x01(\tR\n" +
	"campaignId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\tR\n" +
	"customerId\x12\x19\n" +
	"\bshard_id\x18\x04 \x01(\x05R\ashardId\x12.\n" +
	"\x13ledger_amount_micro\x18\x05 \x01(\x03R\x11ledgerAmountMicro\x12*\n" +
	"\x11redis_delta_micro\x18\x06 \x01(\x03R\x0fredisDeltaMicro\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\".\n" +
	"\x12SupplyFilesPayload\x12\x18\n" +
	"\atrigger\x18\x01 \x01(\tR\atrigger\"3\n" +
	"\x17RtbCatalogReloadPayload\x12\x18\n" +
	"\atrigger\x18\x01 \x01(\tR\atrigger\"1\n" +
	"\x15CohortSnapshotPayload\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\"\xa2\x01\n" +
	"\x18CtvGtaxSettlementPayload\x12#\n" +
	"\rsettlement_id\x18\x01 \x01(\tR\fsettlementId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x1f\n" +
	"\vcampaign_id\x18\x03 \x01(\tR\n" +
	"campaignId\x12\x1f\n" +
	"\vspend_micro\x18\x04 \x01(\x03R\n" +
	"spendMicro\"h\n" +
	"\x14TelegramEventPayload\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\fR\n" +
	"campaignId\x12\x15\n" +
	"\x06bot_id\x18\x02 \x01(\x03R\x05botId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"\xfb\x01\n" +
	"\x14SettleBalancePayload\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12!\n" +
	"\famount_micro\x18\x02 \x01(\x03R\vamountMicro\x124\n" +
	"\x16ledger_idempotency_key\x18\x03 \x01(\tR\x14ledgerIdempotencyKey\x12*\n" +
	"\x11payment_intent_id\x18\x04 \x01(\tR\x0fpaymentIntentId\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x12!\n" +
	"\fprovider_ref\x18\x06 \x01(\tR\vproviderRef\"\xb3\x01\n" +
	"\x11ChargebackPayload\x12*\n" +
	"\x11payment_intent_id\x18\x01 \x01(\tR\x0fpaymentIntentId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12!\n" +
	"\famount_micro\x18\x03 \x01(\x03R\vamountMicro\x12.\n" +
	"\x13provider_dispute_id\x18\x04 \x01(\tR\x11providerDisputeIdBPZNgithub.com/bidshard/ad-event-processor/internal/controlplane/outboxpb;outboxpbb\x06proto3"

var (
	file_outbox_proto_rawDescOnce sync.Once
	file_outbox_proto_rawDescData []byte
)

func file_outbox_proto_rawDescGZIP() []byte {
	file_outbox_proto_rawDescOnce.Do(func() {
		file_outbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_outbox_proto_rawDesc), len(file_outbox_proto_rawDesc)))
	})
	return file_outbox_proto_rawDescData
}

var file_outbox_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_outbox_proto_goTypes = []any{
	(*CampaignPayload)(nil),             // 0: coldpath.v1.CampaignPayload
	(*CampaignIdPayload)(nil),           // 1: coldpath.v1.CampaignIdPayload
	(*BrandIdPayload)(nil),              // 2: coldpath.v1.BrandIdPayload
	(*BrandFcapPayload)(nil),            // 3: coldpath.v1.BrandFcapPayload
	(*CampaignSchedulePayload)(nil),     // 4: coldpath.v1.CampaignSchedulePayload
	(*CampaignPacingPayload)(nil),       // 5: coldpath.v1.CampaignPacingPayload
	(*SettingsPayload)(nil),             // 6: coldpath.v1.SettingsPayload
	(*BlacklistPayload)(nil),            // 7: coldpath.v1.BlacklistPayload
	(*FraudThreatPayload)(nil),          // 8: coldpath.v1.FraudThreatPayload
	(*FraudModelVersionPayload)(nil),    // 9: coldpath.v1.FraudModelVersionPayload
	(*UserConsentPayload)(nil),          // 10: coldpath.v1.UserConsentPayload
	(*PurgeUserDataPayload)(nil),        // 11: coldpath.v1.PurgeUserDataPayload
	(*PausePlacementPayload)(nil),       // 12: coldpath.v1.PausePlacementPayload
	(*QuotaRepairPayload)(nil),          // 13: coldpath.v1.QuotaRepairPayload
	(*ReconciliationAdjustPayload)(nil), // 14: coldpath.v1.ReconciliationAdjustPayload
	(*SupplyFilesPayload)(nil),          // 15: coldpath.v1.SupplyFilesPayload
	(*RtbCatalogReloadPayload)(nil),     // 16: coldpath.v1.RtbCatalogReloadPayload
	(*CohortSnapshotPayload)(nil),       // 17: coldpath.v1.CohortSnapshotPayload
	(*CtvGtaxSettlementPayload)(nil),    // 18: coldpath.v1.CtvGtaxSettlementPayload
	(*TelegramEventPayload)(nil),        // 19: coldpath.v1.TelegramEventPayload
	(*SettleBalancePayload)(nil),        // 20: coldpath.v1.SettleBalancePayload
	(*ChargebackPayload)(nil),           // 21: coldpath.v1.ChargebackPayload
	nil,                                 // 22: coldpath.v1.SettingsPayload.SettingsEntry
}
var file_outbox_proto_depIdxs = []int32{
	22, // 0: coldpath.v1.SettingsPayload.settings:type_name -> coldpath.v1.SettingsPayload.SettingsEntry
	1,  // [1:1] is the sub-list for method output_type
	1,  // [1:1] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_outbox_proto_init() }
func file_outbox_proto_init() {
	if File_outbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_outbox_proto_rawDesc), len(file_outbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_outbox_proto_goTypes,
		DependencyIndexes: file_outbox_proto_depIdxs,
		MessageInfos:      file_outbox_proto_msgTypes,
	}.Build()
	File_outbox_proto = out.File
	file_outbox_proto_goTypes = nil
	file_outbox_proto_depIdxs = nil
}
