package campaign

// CampaignListAllowedSortFields is the canonical allowlist for GET /api/v1/campaigns sort=.
func CampaignListAllowedSortFields() map[string]struct{} {
	return map[string]struct{}{
		"name":           {},
		"spend":          {},
		"updated_at":     {},
		"budget_limit":   {},
		"clicks":         {},
		"impressions":    {},
		"conversions":    {},
		"unique_clicks":  {},
		"blocks":         {},
		"cost":           {},
		"revenue":        {},
		"profit":         {},
		"roi":            {},
		"ctr":            {},
		"cr":             {},
		"cpc":            {},
		"cpa":            {},
		"ecpa":           {},
		"epc":            {},
		"cpm":            {},
		"block_pct":      {},
		"leads":          {},
		"approved":       {},
		"hold_leads":     {},
		"rejected_leads": {},
		"approve_rate":   {},
		"lp_clicks":      {},
		"lp_views":       {},
		"lp_ctr":         {},
		"bots":           {},
		"bot_pct":        {},
		"status":         {},
		"tags":           {},
		"group":          {},
		"flow":           {},
		"owner":          {},
		"countries":      {},
		"budget_pct":     {},
	}
}
