#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
mapfile -t files < <(find "$ROOT" -name '*.go' -not -path '*/vendor/*')

apply() {
  local from="$1" to="$2"
  for f in "${files[@]}"; do
    perl -pi -e "s/\\b${from}\\b/${to}/g" "$f"
  done
}

apply CHQueryConfigFromApp ClickHouseQueryConfigFromApp
apply NewCHPartitionJanitor NewClickHousePartitionJanitor
apply CHPartitionJanitor ClickHousePartitionJanitor
apply CHJanitorOptions ClickHouseJanitorOptions
apply CHTableRetention ClickHouseTableRetention
apply ProcessorCHIngestPolicy ProcessorClickHouseIngestPolicy
apply InitProcessorCHIngestPolicy InitProcessorClickHouseIngestPolicy
apply ProcessorCHStreamMaxWorkers ProcessorClickHouseStreamMaxWorkers
apply ProcessorCHGateSlots ProcessorClickHouseGateSlots
apply ProcessorCHStreamWorkers ProcessorClickHouseStreamWorkers
apply CHQueryMaxConcurrency ClickHouseQueryMaxConcurrency
apply CHQueryTimeoutSec ClickHouseQueryTimeoutSec
apply CHQuerySlowLogMS ClickHouseQuerySlowLogMS
apply CHQueryMaxMemoryBytes ClickHouseQueryMaxMemoryBytes
apply CHQueryMaxExecSec ClickHouseQueryMaxExecSec
apply CHSpoolMaxSegments ClickHouseSpoolMaxSegments
apply CHSpoolSegmentMB ClickHouseSpoolSegmentMB
apply CHReadonlyDSN ClickHouseReadonlyDSN
apply CHRawRetentionDays ClickHouseRawRetentionDays
apply CHEmergencyDropPercent ClickHouseEmergencyDropPercent
apply CHRecompressPartsThreshold ClickHouseRecompressPartsThreshold
apply CHRecompressOffPeakStartUTC ClickHouseRecompressOffPeakStartUTC
apply CHRecompressOffPeakEndUTC ClickHouseRecompressOffPeakEndUTC
apply CHFlushIntervalMs ClickHouseFlushIntervalMs
apply CHJanitorIntervalH ClickHouseJanitorIntervalH
apply CHRetentionDaysRtbDealOutcomes ClickHouseRetentionDaysRtbDealOutcomes
apply CHRetentionDaysRtbExchangeLog ClickHouseRetentionDaysRtbExchangeLog
apply CHSingleRowInsertsTotal ClickHouseSingleRowInsertsTotal
apply CHSpoolAppendDurationSeconds ClickHouseSpoolAppendDurationSeconds
apply CHJanitorRetentionDropTotal ClickHouseJanitorRetentionDropTotal
apply CHJanitorEmergencyDropTotal ClickHouseJanitorEmergencyDropTotal
apply CHJanitorRecompressTotal ClickHouseJanitorRecompressTotal
apply CHQueryDurationSeconds ClickHouseQueryDurationSeconds
apply CHQueryRejectedTotal ClickHouseQueryRejectedTotal
apply CHActivePartsMax ClickHouseActivePartsMax
apply CHSpoolAppendTotal ClickHouseSpoolAppendTotal
apply CHSpoolReplayTotal ClickHouseSpoolReplayTotal
apply CHSpoolRotateTotal ClickHouseSpoolRotateTotal
apply CHSpoolSegments ClickHouseSpoolSegments
apply CHDiskUsedPercent ClickHouseDiskUsedPercent
apply CHHourlyImpressions ClickHouseHourlyImpressions
apply CHUnavailable ClickHouseUnavailable
apply DefaultCHSpoolConfig DefaultClickHouseSpoolConfig
apply OpenCHSpoolWithConfig OpenClickHouseSpoolWithConfig
apply ApplyCHIngestPolicy ApplyClickHouseIngestPolicy
apply NewProcessorChGate NewProcessorClickHouseGate
apply ProcessorChGate ProcessorClickHouseGate
apply ConnectCHReadonly ConnectClickHouseReadonly
apply CHJanitorEnabled ClickHouseJanitorEnabled
apply CHQueryConfig ClickHouseQueryConfig
apply NewCHQuery NewClickHouseQuery
apply ErrCHQueryRejected ErrClickHouseQueryRejected
apply CHSpoolConfig ClickHouseSpoolConfig
apply OpenCHSpool OpenClickHouseSpool
apply CHCfgFromConfig ClickHouseSpoolConfigFromConfig
apply CHSpool ClickHouseSpool
apply CHQuery ClickHouseQuery
apply CHMaxWorkers ClickHouseMaxWorkers
apply CHMaxConns ClickHouseMaxConns
apply CHSpoolDir ClickHouseSpoolDir
apply CHBatchSize ClickHouseBatchSize
apply CHUnixSocket ClickHouseUnixSocket
apply CHIngestSource ClickHouseIngestSource
apply CHDSN ClickHouseDSN
apply CHEnabled ClickHouseEnabled
apply procChGate processorClickHouseGate
apply chJanitor clickhouseJanitor
apply failingCHConn failingClickHouseConn

apply PgFailoverAuditWindowSec PostgresFailoverAuditWindowSec
apply PgFailoverSnapshotSync PostgresFailoverSnapshotSync
apply PgFailoverFailThreshold PostgresFailoverFailThreshold
apply PgFailoverCoordinator PostgresFailoverCoordinator
apply PgFailoverRedisURL PostgresFailoverRedisURL
apply PgFailoverHealthMs PostgresFailoverHealthMs
apply PgFailoverLeaseSec PostgresFailoverLeaseSec
apply PgFailoverCoordMs PostgresFailoverCoordMs
apply PgFailoverPollMs PostgresFailoverPollMs
apply ProcessorPGStreamMaxWorkers ProcessorPostgresStreamMaxWorkers
apply ProcessorPGGateSlots ProcessorPostgresGateSlots
apply ProcessorPGStreamWorkers ProcessorPostgresStreamWorkers
apply PgPoolSettleMaxConns PostgresPoolSettleMaxConns
apply PgPoolSettleConns PostgresPoolSettleConns
apply PgFailoverEnabled PostgresFailoverEnabled
apply PgFailoverSyncPageSize PostgresFailoverSyncPageSize
apply PgPromoteCommand PostgresPromoteCommand
apply PgPrimaryDSN PostgresPrimaryDSN
apply PgStandbyDSN PostgresStandbyDSN
apply newPgFailoverShardReader newPostgresFailoverShardReader
apply pgFailoverShardReader postgresFailoverShardReader
apply pgFailoverFaultInfra postgresFailoverFaultInfra
apply ConnectPgPools ConnectPostgresPools
apply StartPgFailover StartPostgresFailover
apply ClosePgFailover ClosePostgresFailover
apply queryPGRollups queryPostgresRollups
apply isPgUnavailable isPostgresUnavailable
apply withPgHigh withPostgresHigh
apply pgMeterRow postgresMeterRow
apply pgAvailable postgresAvailable
apply PgReserved PostgresReserved
apply PgPools PostgresPools
apply pgPools postgresPools
apply pgFailoverRT postgresFailoverRT

apply tgRedirectMacroBridgeLen telegramRedirectMacroBridgeLen
apply tgRedirectMacroClickLen telegramRedirectMacroClickLen
apply buildTgRedirectLocation buildTelegramRedirectLocation
apply classifyTgLiveResponse classifyTelegramLiveResponse
apply probeTgClick probeTelegramClick
apply parseTgQuery parseTelegramQuery
apply matchTgQueryKey matchTelegramQueryKey
apply tgBridgePayloadSuffix telegramBridgePayloadSuffix
apply tgBridgePayloadPrefix telegramBridgePayloadPrefix
apply tgPathImpression telegramPathImpression
apply tgPathClick telegramPathClick
apply tgQueryParsed telegramQueryParsed
apply TrackerTgClickBaseURL TrackerTelegramClickBaseURL
apply tgMacroBridge telegramMacroBridge
apply tgMacroClick telegramMacroClick
apply tgKeyForbidden telegramKeyForbidden
apply tgKeyBridgeToken telegramKeyBridgeToken
apply tgKeyCampaignID telegramKeyCampaignID
apply tgKeyPlacementID telegramKeyPlacementID
apply tgKeyMotivated telegramKeyMotivated
apply tgKeyBridge telegramKeyBridge
apply tgKeyPremium telegramKeyPremium
apply tgKeyClickID telegramKeyClickID
apply tgKeyUnknown telegramKeyUnknown
apply tgKeyDMR telegramKeyDMR
apply tgKeyID telegramKeyID

for f in "${files[@]}"; do
  perl -pi -e 's/`json:"ch_hourly_impressions/`json:"clickhouse_hourly_impressions/g; s/`json:"ch_unavailable/`json:"clickhouse_unavailable/g; s/`json:"pg_reserved/`json:"postgres_reserved/g' "$f"
done

echo "rename_db_symbols: ok"
