
EXPLAIN (ANALYZE, BUFFERS, FORMAT TEXT)
SELECT * FROM rtb_deals ORDER BY deal_id;

EXPLAIN (ANALYZE, BUFFERS, FORMAT TEXT)
SELECT * FROM rtb_deals WHERE id = 1;

EXPLAIN (ANALYZE, BUFFERS, FORMAT TEXT)
SELECT * FROM rtb_deals WHERE deal_id = 'deal-premium-1';

EXPLAIN (ANALYZE, BUFFERS, FORMAT TEXT)
SELECT * FROM rtb_deals WHERE customer_id = '00000000-0000-4000-8000-000000000001'::uuid;
