package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

var (
	generatedGo = regexp.MustCompile(`(?i)(code generated by|DO NOT EDIT)`)
	skipDirs    = map[string]bool{
		".git": true, "vendor": true, "node_modules": true, "bin": true,
		".cache": true, "dist": true, "api/gen": true, "gen": true,
		".venv": true, "model": true,
	}
)

func main() {
	root := "."
	if len(os.Args) > 1 {
		root = os.Args[1]
	}
	var changed int
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			name := d.Name()
			if skipDirs[name] {
				return filepath.SkipDir
			}
			rel, _ := filepath.Rel(root, path)
			if strings.HasPrefix(rel, "model/") || strings.Contains(rel, "/.venv/") {
				return filepath.SkipDir
			}
			return nil
		}
		base := filepath.Base(path)
		if base == "Makefile" || base == "Dockerfile" || strings.HasSuffix(base, ".mk") {
			ok, err := stripShellFile(path)
			if err != nil {
				return fmt.Errorf("%s: %w", path, err)
			}
			if ok {
				changed++
			}
			return nil
		}
		switch filepath.Ext(path) {
		case ".go":
			ok, err := stripGoFile(path)
			if err != nil {
				return fmt.Errorf("%s: %w", path, err)
			}
			if ok {
				changed++
			}
		case ".sql":
			ok, err := stripSQLFile(path)
			if err != nil {
				return fmt.Errorf("%s: %w", path, err)
			}
			if ok {
				changed++
			}
		case ".css":
			ok, err := stripCSSFile(path)
			if err != nil {
				return fmt.Errorf("%s: %w", path, err)
			}
			if ok {
				changed++
			}
		case ".sh":
			ok, err := stripShellFile(path)
			if err != nil {
				return fmt.Errorf("%s: %w", path, err)
			}
			if ok {
				changed++
			}
		case ".c", ".h":
			ok, err := stripCFile(path)
			if err != nil {
				return fmt.Errorf("%s: %w", path, err)
			}
			if ok {
				changed++
			}
		case ".ts", ".tsx", ".js":
			if strings.Contains(path, "node_modules") {
				return nil
			}
			ok, err := stripJSFile(path)
			if err != nil {
				return fmt.Errorf("%s: %w", path, err)
			}
			if ok {
				changed++
			}
		case ".yml", ".yaml":
			ok, err := stripShellFile(path)
			if err != nil {
				return fmt.Errorf("%s: %w", path, err)
			}
			if ok {
				changed++
			}
		}
		return nil
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("changed %d files\n", changed)
}

func isGeneratedGo(path string, src []byte) bool {
	if generatedGo.Match(src) {
		return true
	}
	base := filepath.Base(path)
	if strings.HasSuffix(base, ".pb.go") ||
		strings.HasSuffix(base, "_grpc.pb.go") ||
		strings.HasSuffix(base, "_vtproto.pb.go") ||
		strings.Contains(base, "_bpf") && strings.HasSuffix(base, ".go") {
		return true
	}
	if strings.HasSuffix(base, ".sql.go") ||
		base == "db.go" || base == "models.go" || base == "querier.go" {
		if strings.Contains(path, "/db/") || strings.Contains(path, "internal/domain/db") {
			return true
		}
	}
	return false
}

func isGoDirective(text string) bool {
	text = strings.TrimSpace(text)
	if !strings.HasPrefix(text, "//") {
		return false
	}
	body := strings.TrimSpace(strings.TrimPrefix(text, "//"))
	return strings.HasPrefix(body, "go:") ||
		strings.HasPrefix(body, "+build") ||
		strings.HasPrefix(body, "line ") ||
		strings.HasPrefix(body, "export ") ||
		strings.HasPrefix(body, "sys ") ||
		strings.HasPrefix(body, "nolint") ||
		strings.HasPrefix(body, "garble:")
}

func clearGoDocComments(node ast.Node) {
	ast.Inspect(node, func(n ast.Node) bool {
		switch x := n.(type) {
		case *ast.File:
			x.Doc = nil
		case *ast.FuncDecl:
			x.Doc = nil
		case *ast.GenDecl:
			x.Doc = nil
			for _, spec := range x.Specs {
				switch s := spec.(type) {
				case *ast.TypeSpec:
					s.Doc, s.Comment = nil, nil
				case *ast.ValueSpec:
					s.Doc, s.Comment = nil, nil
				case *ast.ImportSpec:
					s.Doc, s.Comment = nil, nil
				}
			}
		case *ast.Field:
			x.Doc, x.Comment = nil, nil
		}
		return true
	})
}

func stripGoFile(path string) (bool, error) {
	src, err := os.ReadFile(path)
	if err != nil {
		return false, err
	}
	if isGeneratedGo(path, src) {
		return false, nil
	}
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, src, parser.ParseComments)
	if err != nil {
		return false, nil
	}
	var kept []*ast.CommentGroup
	for _, cg := range f.Comments {
		var list []*ast.Comment
		for _, c := range cg.List {
			if isGoDirective(c.Text) {
				list = append(list, c)
			}
		}
		if len(list) > 0 {
			kept = append(kept, &ast.CommentGroup{List: list})
		}
	}
	f.Comments = kept
	clearGoDocComments(f)
	ast.SortImports(fset, f)
	var buf bytes.Buffer
	cfg := printer.Config{Mode: printer.UseSpaces | printer.TabIndent, Tabwidth: 8}
	if err := cfg.Fprint(&buf, fset, f); err != nil {
		return false, err
	}
	out, err := format.Source(buf.Bytes())
	if err != nil {
		out = buf.Bytes()
	}
	if bytes.Equal(src, out) {
		return false, nil
	}
	return true, os.WriteFile(path, out, 0o644)
}

func stripSQLFile(path string) (bool, error) {
	src, err := os.ReadFile(path)
	if err != nil {
		return false, err
	}
	lines := strings.Split(string(src), "\n")
	out := make([]string, 0, len(lines))
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "-- +goose") {
			out = append(out, line)
			continue
		}
		if idx := strings.Index(line, "--"); idx >= 0 {
			before := strings.TrimSpace(line[:idx])
			if before == "" {
				continue
			}
			line = strings.TrimRight(line[:idx], " \t")
		}
		if strings.TrimSpace(line) != "" || len(out) > 0 {
			out = append(out, line)
		}
	}
	result := strings.Join(out, "\n")
	if len(out) > 0 && !strings.HasSuffix(result, "\n") && strings.HasSuffix(string(src), "\n") {
		result += "\n"
	}
	if string(src) == result {
		return false, nil
	}
	return true, os.WriteFile(path, []byte(result), 0o644)
}

var cssBlockComment = regexp.MustCompile(`/\*[\s\S]*?\*/`)

func stripCSSFile(path string) (bool, error) {
	src, err := os.ReadFile(path)
	if err != nil {
		return false, err
	}
	out := cssBlockComment.ReplaceAll(src, nil)
	out = bytes.TrimSpace(out)
	if len(out) > 0 {
		out = append(out, '\n')
	}
	if bytes.Equal(src, out) {
		return false, nil
	}
	return true, os.WriteFile(path, out, 0o644)
}

func stripShellFile(path string) (bool, error) {
	src, err := os.ReadFile(path)
	if err != nil {
		return false, err
	}
	lines := strings.Split(string(src), "\n")
	out := make([]string, 0, len(lines))
	for i, line := range lines {
		if i == 0 && strings.HasPrefix(strings.TrimSpace(line), "#!") {
			out = append(out, line)
			continue
		}
		if cut := shellCommentStart(line); cut >= 0 {
			line = strings.TrimRight(line[:cut], " \t")
		}
		out = append(out, line)
	}
	result := strings.Join(out, "\n")
	if string(src) == result {
		return false, nil
	}
	return true, os.WriteFile(path, []byte(result), 0o644)
}

func shellCommentStart(line string) int {
	inSingle := false
	inDouble := false
	for i := 0; i < len(line); i++ {
		switch line[i] {
		case '\'':
			if !inDouble {
				inSingle = !inSingle
			}
		case '"':
			if !inSingle {
				inDouble = !inDouble
			}
		case '#':
			if !inSingle && !inDouble {
				return i
			}
		}
	}
	return -1
}

var cBlockComment = regexp.MustCompile(`/\*[\s\S]*?\*/`)

func stripCFile(path string) (bool, error) {
	src, err := os.ReadFile(path)
	if err != nil {
		return false, err
	}
	out := cBlockComment.ReplaceAll(src, nil)
	lines := strings.Split(string(out), "\n")
	clean := make([]string, 0, len(lines))
	for _, line := range lines {
		if idx := strings.Index(line, "//"); idx >= 0 {
			line = strings.TrimRight(line[:idx], " \t")
		}
		clean = append(clean, line)
	}
	result := strings.Join(clean, "\n")
	if string(src) == result {
		return false, nil
	}
	return true, os.WriteFile(path, []byte(result), 0o644)
}

func isJSDirective(trimmed string) bool {
	return strings.HasPrefix(trimmed, "// @ts-") ||
		strings.HasPrefix(trimmed, "//@ts-") ||
		strings.HasPrefix(trimmed, "/// <reference") ||
		strings.HasPrefix(trimmed, "// eslint-disable") ||
		strings.HasPrefix(trimmed, "/* eslint-disable") ||
		strings.HasPrefix(trimmed, "/* global ")
}

func stripJSFile(path string) (bool, error) {
	src, err := os.ReadFile(path)
	if err != nil {
		return false, err
	}
	out := stripJSComments(string(src))
	if string(src) == out {
		return false, nil
	}
	return true, os.WriteFile(path, []byte(out), 0o644)
}

func stripJSComments(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	i := 0
	for i < len(s) {
		if s[i] == '"' || s[i] == '\'' || s[i] == '`' {
			quote := s[i]
			b.WriteByte(quote)
			i++
			for i < len(s) {
				if s[i] == '\\' && i+1 < len(s) {
					b.WriteByte(s[i])
					b.WriteByte(s[i+1])
					i += 2
					continue
				}
				b.WriteByte(s[i])
				if s[i] == quote {
					i++
					break
				}
				i++
			}
			continue
		}
		if i+1 < len(s) && s[i] == '/' && s[i+1] == '/' {
			end := strings.IndexByte(s[i:], '\n')
			if end < 0 {
				line := strings.TrimSpace(s[i:])
				if isJSDirective(line) {
					b.WriteString(s[i:])
				}
				return strings.TrimRight(b.String(), " \t") + "\n"
			}
			line := strings.TrimSpace(s[i : i+end])
			if isJSDirective(line) {
				b.WriteString(s[i : i+end+1])
			}
			i += end + 1
			continue
		}
		if i+1 < len(s) && s[i] == '/' && s[i+1] == '*' {
			end := strings.Index(s[i+2:], "*/")
			if end < 0 {
				break
			}
			block := strings.TrimSpace(s[i : i+end+4])
			if isJSDirective(block) {
				b.WriteString(s[i : i+end+4])
			}
			i += end + 4
			continue
		}
		b.WriteByte(s[i])
		i++
	}
	return b.String()
}
